// Prueba los SQL de supabase/ en un Postgres local, sin tocar el proyecto real.
// Uso: npm run test:sql
import { altaUsuario, crearAcceso, crearBase } from './supabase-local.mjs'

const db = await crearBase()
const x = crearAcceso(db)
let fallas = 0
const ok = (cond, texto) => { console.log(`${cond ? '  ✓' : '  ✗'} ${texto}`); if (!cond) fallas++ }
const falla = async (texto, fn) => {
  try { await fn(); ok(false, `${texto} (tenía que fallar y no falló)`) } catch (e) { ok(true, `${texto} → "${String(e.message).slice(0, 60)}"`) }
}
const titulo = (t) => console.log(`\n${t}`)

// =============================== Perfiles ===================================

const A = { id: '00000000-0000-0000-0000-00000000000a', usuario: 'lauti_hax', nombre: 'Lauti' }
const B = { id: '00000000-0000-0000-0000-00000000000b', usuario: 'pepito', nombre: 'Pepito' }
await x.admin(`insert into auth.users values ($1), ($2)`, [A.id, B.id])

titulo('Perfil')
const a1 = await x.rpc(A, 'mi_perfil')
ok(a1.username === 'lauti_hax' && a1.nick === 'Lauti', 'la primera vez crea el perfil con el usuario y el nombre visible de Discord')
ok(/^HX[A-HJ-NP-Z2-9]{4}$/.test(a1.codigo), `genera un código de referido (${a1.codigo})`)
ok(a1.onboarding === false, 'arranca con el registro sin terminar')
const a2 = await x.rpc({ ...A, usuario: 'otro', nombre: 'Otro' }, 'mi_perfil')
ok(a2.codigo === a1.codigo && a2.nick === 'Lauti', 'volver a entrar no crea otro perfil ni cambia el código')
await falla('un visitante no puede pedir un perfil', () => x.rpc(null, 'mi_perfil'))

titulo('Registro')
await falla('rechaza un nick de un carácter', () => x.rpc(A, 'completar_registro', { p_nick: 'X', p_region: ['ARG'] }))
await falla('rechaza una región que no existe', () => x.rpc(A, 'completar_registro', { p_nick: 'Lauti10', p_region: ['MX'] }))
await falla('rechaza quedarse sin región', () => x.rpc(A, 'completar_registro', { p_nick: 'Lauti10', p_region: [] }))
const a3 = await x.rpc(A, 'completar_registro', { p_nick: 'Lauti10', p_region: ['ARG', 'UY'], p_codigo: a1.codigo })
ok(a3.nick === 'Lauti10' && a3.onboarding === true && a3.region.join() === 'ARG,UY', 'guarda nick y regiones y termina el registro')
ok(a3.referido_por === null, 'no deja usar el código propio')
ok((await x.rpc(A, 'completar_registro', { p_nick: '', p_region: ['ARG'] })).nick === 'lauti_hax', 'sin nick usa el usuario de Discord')

titulo('Código de un amigo')
ok(await x.rpc(null, 'quien_invita', { p_codigo: ` ${a1.codigo.toLowerCase()} ` }) === 'lauti_hax', 'un visitante puede validar un código (sin importar mayúsculas ni espacios)')
ok(await x.rpc(null, 'quien_invita', { p_codigo: 'NOEXISTE' }) === null, 'un código que no existe devuelve vacío')
await x.rpc(B, 'mi_perfil')
const b1 = await x.rpc(B, 'completar_registro', { p_nick: 'Pepito', p_region: ['CHI'], p_codigo: a1.codigo })
ok(b1.referido_por === A.id && b1.invito === 'lauti_hax', 'una cuenta nueva queda anotada como invitada por el dueño del código')
ok((await x.rpc(B, 'completar_registro', { p_nick: 'Pepito', p_region: ['CHI'], p_codigo: 'OTRO99' })).referido_por === A.id, 'una cuenta que ya terminó el registro no puede cambiar quién la invitó')

titulo('Permisos de perfiles')
ok((await x.sql(B, 'select id, username, nick, region, foto_url from public.profiles')).length === 2, 'un usuario ve los datos públicos de los demás')
await falla('no puede leer quién invitó a otro', () => x.sql(B, 'select referido_por from public.profiles'))
await falla('un visitante no puede leer perfiles', () => x.sql(null, 'select nick from public.profiles'))
await x.sql(B, `update public.profiles set nick = 'Hackeado' where id = '${A.id}'`)
ok((await x.rpc(A, 'mi_perfil')).nick === 'lauti_hax', 'no puede cambiar el perfil de otro')
await x.sql(B, `update public.profiles set foto_url = 'https://ejemplo/foto.jpg', nick = 'Pepe' where id = '${B.id}'`)
ok((await x.rpc(B, 'mi_perfil')).nick === 'Pepe', 'sí puede cambiar su foto y su nick')
await falla('no puede cambiarse el código', () => x.sql(B, `update public.profiles set codigo = 'HXAAAA' where id = '${B.id}'`))
await falla('no puede insertar perfiles a mano', () => x.sql(B, `insert into public.profiles (id, username, nick, codigo) values ('${B.id}', 'x', 'xx', 'HX0000')`))

titulo('Fotos')
await x.sql(A, `insert into storage.objects (bucket_id, name) values ('avatares', '${A.id}/foto.jpg')`)
ok(true, 'puede subir una foto a su propia carpeta')
await falla('no puede subir una foto a la carpeta de otro', () => x.sql(B, `insert into storage.objects (bucket_id, name) values ('avatares', '${A.id}/foto.jpg')`))
ok((await x.sql(B, `delete from storage.objects where bucket_id = 'avatares' returning id`)).length === 0, 'no puede borrar la foto de otro')

// ================================= Cola =====================================

const ana = await altaUsuario(x, 1, 'ana')
const beto = await altaUsuario(x, 2, 'beto')
const caro = await altaUsuario(x, 3, 'caro')
const dani = await altaUsuario(x, 4, 'dani')
const eva = await altaUsuario(x, 5, 'eva')
const fran = await altaUsuario(x, 6, 'fran', 'fran', ['CHI'])

const jugador = (u, extra = {}) => x.rpc(u, 'crear_busqueda', { p_modo: 'jugador', p_formato: ['3v3'], p_posicion: ['Polifuncional'], p_cancha: ['Cualquiera'], p_region: ['ARG'], p_duracion: '15min', ...extra })
const sala = (u, faltan, extra = {}) => x.rpc(u, 'crear_busqueda', { p_modo: 'sala', p_formato: null, p_posicion: ['Polifuncional'], p_cancha: ['Cualquiera'], p_region: ['ARG'], p_nombre_sala: `sala de ${u.usuario}`, p_faltan: faltan, ...extra })
const estado = (u) => x.rpc(u, 'estado_cola')
const mia = async (u) => (await estado(u)).busquedas.find((b) => b.user_id === u.id)
const pedido = async (u) => (await estado(u)).mensajes.find((m) => m.a === u.id && m.estado === 'pendiente')
const partido = async (u) => (await estado(u)).matches[0]
const limpiar = async () => {
  for (const u of [ana, beto, caro, dani, eva, fran]) await x.rpc(u, 'cancelar_busqueda')
  await x.admin(`update public.busquedas set estado = 'cancelada' where estado in ('activa', 'agrupada', 'match')`)
  await x.admin(`delete from public.matches`)
  await x.admin(`delete from public.mensajes`)
}

titulo('Búsquedas')
await falla('sin terminar el registro no se puede buscar', async () => {
  const nuevo = { id: '00000000-0000-0000-0000-000000000099', usuario: 'nuevo' }
  await x.admin(`insert into auth.users values ($1)`, [nuevo.id]); await x.rpc(nuevo, 'mi_perfil'); await jugador(nuevo)
})
await jugador(beto)
ok((await mia(beto)).estado === 'activa' && (await mia(beto)).expira_at !== null, 'un jugador se pone disponible por 15 minutos')
await falla('una sola búsqueda activa por usuario', () => sala(beto, 2))
await falla('una sala necesita nombre', () => sala(ana, 2, { p_nombre_sala: '  ' }))
await falla('una sala no puede pedir 8 jugadores', () => sala(ana, 8))
await falla('no acepta una cancha inventada', () => jugador(caro, { p_cancha: ['Cancha rara'] }))
ok((await estado(caro)).busquedas.length === 1 && (await estado(caro)).usuarios.some((u) => u.nick === 'beto'), 'los demás ven la búsqueda y quién la hizo')
await x.rpc(beto, 'cancelar_busqueda')
ok((await estado(caro)).busquedas.length === 0, 'al cancelar desaparece de la cola')
await falla('un visitante no puede ver la cola', () => x.rpc(null, 'estado_cola'))
await falla('nadie puede leer las tablas directo', () => x.sql(beto, 'select * from public.busquedas'))
await falla('nadie puede escribir las tablas directo', () => x.sql(beto, `update public.match_participantes set confirmado_at = now()`))
await falla('la app no puede llamar a las funciones internas', () => x.sql(beto, `select public._ocupar(gen_random_uuid(), array[]::uuid[], 'B')`))
ok((await x.sql(beto, 'select version from public.cambios')).length === 1, 'la señal de cambios sí se puede leer')

titulo('Sala: la app acerca jugadores, el dueño acepta, entra y confirma')
await limpiar()
await sala(ana, 2)
await jugador(beto)
let p = await pedido(ana)
ok(p && p.auto && p.de === beto.id, 'al aparecer un jugador compatible, la app se lo acerca a la sala')
ok(!(await estado(beto)).matches.length, 'hasta que el dueño acepte no hay match')
await falla('solo el dueño de la sala puede responder ese pedido', () => x.rpc(caro, 'responder_mensaje', { p_id: p.id, p_aceptar: true }))
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
let m = await partido(beto)
ok(m && m.creado_por === ana.id && m.nombre_sala === 'sala de ana', 'al aceptar, el jugador recibe el match con el nombre de la sala')
ok((await mia(ana)).faltan === 1 && (await mia(ana)).estado === 'activa', 'la sala sigue buscando: le falta 1')
ok(!(await mia(beto)), 'la búsqueda del jugador se cerró')
await falla('el que entra no puede marcar quién entró', () => x.rpc(beto, 'marcar_entro', { p_user: ana.id }))
await x.rpc(ana, 'marcar_entro', { p_user: beto.id })
m = await partido(ana)
ok(m.contado_at === null && m.participantes.find((q) => q.user_id === beto.id).entro_at !== null, '"Ya entró" queda anotado; el partido todavía no cuenta')
await x.rpc(beto, 'confirmar_match', { p_match: m.id })
ok((await partido(ana)).contado_at !== null, 'cuando confirma el que entró, el partido cuenta')
await falla('uno de afuera no puede confirmar el partido', () => x.rpc(caro, 'confirmar_match', { p_match: m.id }))

titulo('Sala: rechazar y "Se salió"')
await jugador(caro)
p = await pedido(ana)
ok(p && p.de === caro.id, 'con un lugar libre, la app acerca al siguiente')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: false })
ok((await mia(ana)).rechazados.includes(caro.id) && !(await pedido(ana)), 'al rechazarlo, no se lo vuelve a acercar')
ok((await mia(caro)).estado === 'activa', 'el rechazado sigue buscando')
await x.rpc(ana, 'marcar_salio', { p_user: beto.id })
ok((await mia(ana)).faltan === 2, '"Se salió" libera el lugar')
ok((await partido(ana)).contado_at !== null, 'el partido que ya contó no se pierde')
ok((await partido(ana)).participantes.find((q) => q.user_id === beto.id)?.salio_at != null, 'el que se fue deja el lugar, pero sigue figurando en el partido')
ok((await estado(beto)).resumen.jugados === 1 && (await partido(beto))?.contado_at !== null, 'y a él el partido le sigue contando')
await falla('otro usuario no puede sacar gente de una sala ajena', () => x.rpc(caro, 'marcar_salio', { p_user: ana.id, p_match: m.id }))

titulo('Sala completa: se cierra sola cuando entraron todos')
await limpiar()
await sala(ana, 1)
await jugador(beto)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
ok((await mia(ana)).faltan === 0 && (await mia(ana)).completa_at !== null, 'al llenarse queda marcada como completa (reloj quieto)')
await jugador(caro)
ok(!(await pedido(ana)), 'a una sala completa no se le acerca a nadie')
await x.rpc(ana, 'marcar_entro', { p_user: beto.id })
ok(!(await mia(ana)), 'completa y con todos adentro: la búsqueda se cierra')
m = await partido(ana)
await x.rpc(ana, 'marcar_salio', { p_user: beto.id, p_match: m.id })
ok((await mia(ana))?.faltan === 1 && !(await estado(ana)).matches.length, 'si se va antes de que cuente, la sala se reabre y no queda partido')
ok((await pedido(ana))?.de === caro.id, 'y la app vuelve a acercarle gente')

titulo('Mensajes: jugador a sala y sala a jugador')
await limpiar()
await sala(ana, 1, { p_region: ['UY'] })
await jugador(beto)
ok(!(await pedido(ana)), 'sin región en común la app no los acerca')
await x.rpc(beto, 'enviar_mensaje', { p_a: ana.id })
p = await pedido(ana)
ok(p && !p.auto && p.texto === '¿Me sumo a tu sala?', 'pero el jugador puede escribirle igual a la sala')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
ok((await partido(beto))?.creado_por === ana.id, 'si la sala acepta, hay match aunque no fuera lo que buscaba')
await limpiar()
await sala(ana, 2)
await jugador(fran, { p_region: ['CHI'] })
await x.rpc(ana, 'enviar_mensaje', { p_a: fran.id })
p = await pedido(fran)
ok(p?.texto === '¿Te sumás a mi sala?', 'la sala puede invitar a un jugador')
await x.rpc(fran, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
ok((await partido(fran))?.creado_por === ana.id && (await mia(ana)).faltan === 1, 'si el jugador acepta, entra directo (la sala ya lo eligió)')
await falla('no se le puede escribir a alguien que no está buscando', () => x.rpc(beto, 'enviar_mensaje', { p_a: fran.id }))
await falla('no se puede escribir a uno mismo', () => x.rpc(beto, 'enviar_mensaje', { p_a: beto.id }))

titulo('Grupos: el que acepta se suma a la búsqueda y al reloj del otro')
await limpiar()
await jugador(beto, { p_formato: ['4v4'] })
await jugador(caro, { p_formato: ['4v4'] })
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
p = await pedido(caro)
ok(p?.texto === '¿Jugamos un 4v4?', 'un jugador invita a otro')
await x.rpc(caro, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
let bc = await mia(caro)
ok(bc.estado === 'agrupada' && bc.lider_id === (await mia(beto)).id, 'el que acepta queda sumado a la búsqueda del que escribió')
ok(!(await estado(dani)).matches.length && (await mia(beto)).estado === 'activa', 'no hay match: siguen buscando juntos')
await falla('solo quien armó el grupo puede escribirles a otros', () => x.rpc(caro, 'enviar_mensaje', { p_a: dani.id }))
await sala(ana, 1)
ok(!(await pedido(ana)), 'un grupo de 2 no se acerca a una sala a la que le falta 1')
await falla('ni puede escribirle: no entran todos', () => x.rpc(beto, 'enviar_mensaje', { p_a: ana.id }))
await x.rpc(caro, 'cancelar_busqueda')
ok(!(await mia(caro)) && (await mia(beto)).estado === 'activa', 'un sumado puede irse del grupo sin cortar la búsqueda del otro')
ok((await pedido(ana))?.de === beto.id, 'y al quedar solo, la app sí lo acerca a la sala de 1')

titulo('Prioridad: el grupo del tamaño justo le gana a los jugadores sueltos')
await limpiar()
await jugador(dani)
await jugador(beto, { p_formato: ['4v4'] })
await jugador(caro, { p_formato: ['4v4'] })
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
await sala(ana, 2)
p = await pedido(ana)
ok(p?.de === beto.id && p.con.length === 1 && p.con[0] === caro.id, 'a una sala a la que le faltan 2 le llega primero el grupo de 2, aunque el suelto buscaba desde antes')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
m = await partido(caro)
ok(m?.participantes.length === 3 && (await mia(ana)).faltan === 0, 'al aceptar entra el grupo completo y la sala queda llena')
ok(!(await mia(beto)) && !(await mia(caro)), 'la búsqueda de los dos se cerró')
ok((await mia(dani)).estado === 'activa', 'el suelto sigue buscando')
await x.rpc(ana, 'marcar_entro', { p_user: beto.id })
await x.rpc(caro, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).contado_at !== null, 'alcanza con que confirme uno de los que entraron: cuenta para todos')

titulo('Equipo completo: arma sala y busca rival')
await limpiar()
await jugador(beto)
await jugador(caro)
await jugador(dani)
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
ok((await mia(beto)).equipo_listo === false, 'dos buscando 3v3 todavía no son un equipo')
await x.rpc(beto, 'enviar_mensaje', { p_a: dani.id })
await x.rpc(dani, 'responder_mensaje', { p_id: (await pedido(dani)).id, p_aceptar: true })
ok((await mia(beto)).equipo_listo === true, 'tres buscando 3v3 ya son un equipo completo')
await sala(ana, 3)
p = await pedido(ana)
ok(p?.de === beto.id && p.con.length === 2, 'un equipo completo de 3 es justo lo que necesita una sala a la que le faltan 3: la app se lo acerca')
await x.rpc(ana, 'cancelar_busqueda')
ok(!(await pedido(ana)) && (await mia(beto)).equipo_listo, 'si esa sala se va, el equipo sigue completo y puede armar la suya')
await falla('un sumado no puede crear la sala del grupo', () => x.rpc(caro, 'convertir_en_sala', { p_nombre: 'x', p_faltan: 3 }))
await x.rpc(beto, 'convertir_en_sala', { p_nombre: 'equipo beto', p_faltan: 3 })
let sb = await mia(beto)
ok(sb.modo === 'sala' && sb.faltan === 3 && sb.nombre_sala === 'equipo beto', 'quien armó el grupo crea la sala y pasan a buscar 3')
m = await partido(caro)
ok(m.participantes.filter((q) => q.equipo === 'A').length === 3, 'los tres quedan del mismo lado')
await x.rpc(beto, 'marcar_entro', { p_user: caro.id })
await x.rpc(caro, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).contado_at === null, 'entre compañeros no alcanza: falta que confirme un rival')
await jugador(eva)
await x.rpc(beto, 'responder_mensaje', { p_id: (await pedido(beto)).id, p_aceptar: true })
await x.rpc(eva, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).contado_at !== null, 'cuando entra y confirma un rival, el partido cuenta')

titulo('Jugar entre nosotros')
await limpiar()
await jugador(beto, { p_formato: ['Cualquiera'] })
await jugador(caro, { p_formato: ['Cualquiera'] })
await falla('solo no se puede jugar "entre nosotros"', () => x.rpc(beto, 'convertir_en_sala', { p_nombre: 'solo', p_faltan: 0, p_entre_nosotros: true }))
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
ok((await mia(beto)).equipo_listo === false, 'con "Cualquiera" el grupo nunca se completa solo')
await x.rpc(beto, 'convertir_en_sala', { p_nombre: 'mano a mano', p_faltan: 0, p_entre_nosotros: true })
ok((await mia(beto)).faltan === 0, 'la sala queda completa: no busca a nadie más')
m = await partido(caro)
await x.rpc(beto, 'marcar_entro', { p_user: caro.id })
ok(!(await mia(beto)), 'al entrar el otro, la búsqueda se cierra')
await x.rpc(caro, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).contado_at !== null, 'son rivales entre ellos: con los dos confirmando, cuenta')

titulo('Quien arma el grupo cancela, y cartel de los 15 minutos')
await limpiar()
await jugador(beto)
await jugador(caro)
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
await x.rpc(beto, 'cancelar_busqueda')
bc = await mia(caro)
ok(bc.estado === 'activa' && bc.lider_id === null, 'si cancela quien armó el grupo, los sumados vuelven a la cola por su cuenta')
ok(new Date(bc.expira_at) - new Date((await estado(caro)).ahora) > 14 * 60 * 1000, 'y arrancan con 15 minutos nuevos')
await x.admin(`update public.busquedas set expira_at = now() - interval '1 minute' where user_id = $1 and estado = 'activa'`, [caro.id])
ok((await mia(caro))?.estado === 'activa', 'al cumplirse los 15 minutos hay 2 de gracia para responder el cartel')
await x.rpc(caro, 'renovar_busqueda')
ok(new Date((await mia(caro)).expira_at) > new Date(), 'renovar da 15 minutos más')
await x.admin(`update public.busquedas set expira_at = now() - interval '3 minutes' where user_id = $1 and estado = 'activa'`, [caro.id])
ok(!(await mia(caro)), 'pasada la gracia, la búsqueda vence sola')

titulo('Sin señales de vida')
await limpiar()
await jugador(beto, { p_duracion: 'match' })
await sala(ana, 2)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
await jugador(caro, { p_duracion: 'match' })
await x.admin(`update public.busquedas set visto_at = now() - interval '11 minutes' where user_id in ($1, $2)`, [ana.id, caro.id])
const e = await estado(dani)
ok(!e.busquedas.some((b) => b.user_id === caro.id), 'una búsqueda cuyo dueño no aparece hace 10 minutos sale de la cola')
ok(!e.busquedas.some((b) => b.user_id === ana.id) && (await partido(beto)), 'una sala con gente adentro se cierra, pero el partido queda')

titulo('Pendientes')
m = await partido(beto)
await x.rpc(beto, 'descartar_match', { p_match: m.id })
ok((await partido(beto)).participantes.find((q) => q.user_id === beto.id).descarto === true, '"No lo jugué" queda anotado solo para quien lo dijo')
await x.rpc(beto, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).participantes.find((q) => q.user_id === beto.id).confirmado_at !== null, 'después se puede confirmar igual')
ok((await partido(beto)).contado_at === null, 'pero no cuenta hasta que confirme el otro lado')

titulo('Varias salas, un jugador')
await limpiar()
await sala(ana, 1)
await sala(dani, 1)
await jugador(beto)
ok((await pedido(ana))?.de === beto.id && (await pedido(dani))?.de === beto.id, 'el mismo jugador queda propuesto a las dos salas')
await x.rpc(dani, 'responder_mensaje', { p_id: (await pedido(dani)).id, p_aceptar: true })
ok((await partido(beto))?.creado_por === dani.id && !(await pedido(ana)), 'entra a la primera que lo acepta y el otro pedido se cae')
await falla('la otra sala ya no puede aceptarlo', async () => {
  const viejo = (await estado(ana)).mensajes.find((q) => q.de === beto.id)
  await x.rpc(ana, 'responder_mensaje', { p_id: viejo.id, p_aceptar: true })
})

titulo('Resumen del perfil y reportes')
ok((await estado(dani)).resumen.jugados === 0, 'un partido sin confirmar no cuenta como jugado')
m = await partido(dani)
await x.rpc(dani, 'marcar_entro', { p_user: beto.id })
await x.rpc(beto, 'confirmar_match', { p_match: m.id })
ok((await estado(dani)).resumen.jugados === 1 && (await estado(beto)).resumen.jugados === 1, 'al confirmarse suma un jugado para los dos')
await x.rpc(beto, 'reportar', { p_user: dani.id, p_motivo: 'No apareció', p_detalle: 'nunca entró' })
ok((await x.admin('select * from public.reportes')).length === 1, 'un reporte queda guardado')
await falla('no se puede reportar a uno mismo', () => x.rpc(beto, 'reportar', { p_user: beto.id, p_motivo: 'No apareció' }))
await falla('el motivo tiene que ser uno de la lista', () => x.rpc(beto, 'reportar', { p_user: dani.id, p_motivo: 'Porque sí' }))
await falla('los reportes no se pueden leer desde la app', () => x.sql(beto, 'select * from public.reportes'))

titulo('Nadie ocupa dos lugares en la misma sala')
await limpiar()
await sala(ana, 3)
await jugador(beto)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
await jugador(beto)
ok(!(await pedido(ana)) && (await mia(ana)).faltan === 2, 'si el que ya entró vuelve a buscar, la app no se lo acerca de nuevo a esa sala')
await falla('ni puede escribirle para entrar otra vez', () => x.rpc(beto, 'enviar_mensaje', { p_a: ana.id }))
await falla('ni la sala puede invitarlo de nuevo', () => x.rpc(ana, 'enviar_mensaje', { p_a: beto.id }))
await x.rpc(beto, 'cancelar_busqueda')

titulo('El partido le cuenta a cada uno cuando entró o confirmó')
await x.rpc(ana, 'marcar_entro', { p_user: beto.id })
m = await partido(ana)
await x.rpc(beto, 'confirmar_match', { p_match: m.id })
ok((await partido(ana)).contado_at !== null && (await partido(beto)).contado_at !== null, 'con uno de cada lado, el partido cuenta')
await jugador(caro)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
ok((await partido(caro)).contado_at === null && (await estado(caro)).resumen.jugados === 0, 'al que aceptan después no le cuenta por el solo hecho de estar anotado')
await x.rpc(ana, 'marcar_entro', { p_user: caro.id })
ok((await partido(caro)).contado_at !== null && (await estado(caro)).resumen.jugados === 1, 'le cuenta cuando el dueño marca que entró (o cuando confirma)')
await x.rpc(ana, 'marcar_salio', { p_user: caro.id })
ok((await estado(caro)).resumen.jugados === 1 && (await mia(ana)).faltan === 2, '"Se salió" después de contar libera el lugar sin sacarle el partido')
await jugador(caro)
p = await pedido(ana)
ok(p?.de === caro.id, 'el que se fue puede volver a esa sala')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
ok((await partido(ana)).participantes.find((q) => q.user_id === caro.id).salio_at === null && (await mia(ana)).faltan === 1, 'y vuelve a ocupar un lugar')

titulo('"No vino" y salas cerradas')
await jugador(dani)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
ok((await mia(ana)).faltan === 0, 'la sala se llenó')
await x.rpc(ana, 'marcar_salio', { p_user: dani.id })
ok((await mia(ana)).faltan === 1 && !(await estado(dani)).matches.length, 'al que nunca entró se lo puede sacar: se libera el lugar y a él no le queda nada')
await x.rpc(ana, 'cancelar_busqueda')
ok(!(await mia(ana)) && (await partido(ana)), 'cerrar la sala con gente adentro deja el partido')
await x.rpc(ana, 'marcar_salio', { p_user: caro.id, p_match: (await partido(ana)).id })
ok(!(await mia(ana)), 'una sala que cerró su dueño no se reabre con "Se salió"')

titulo('Mensajes que dejan de tener sentido')
await limpiar()
await falla('sin estar buscando no se puede escribir', async () => { await sala(ana, 2); await x.rpc(dani, 'enviar_mensaje', { p_a: ana.id }) })
await jugador(beto, { p_region: ['CHI'] })
await jugador(caro, { p_region: ['CHI'] })
await x.rpc(beto, 'enviar_mensaje', { p_a: ana.id })
ok((await pedido(ana))?.con.length === 0, 'un jugador solo le escribe a una sala')
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
p = await pedido(ana)
ok(p?.con.length === 1 && p.con[0] === caro.id && p.texto === '¿Entramos 2 a tu sala?', 'si después suma a alguien a su grupo, el pedido se actualiza')
await jugador(dani, { p_region: ['CHI'] })
await x.rpc(beto, 'enviar_mensaje', { p_a: dani.id })
await x.rpc(dani, 'responder_mensaje', { p_id: (await pedido(dani)).id, p_aceptar: true })
ok(!(await pedido(ana)), 'y si ya no entran todos, el pedido se cae solo')
await x.rpc(beto, 'cancelar_busqueda'); await x.rpc(caro, 'cancelar_busqueda'); await x.rpc(dani, 'cancelar_busqueda')
await jugador(eva)
p = await pedido(ana)
ok(p?.auto && p.de === eva.id, 'la sala no quedó trabada: la app le acerca al siguiente')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: null })
ok((await mia(ana)).faltan === 2 && !(await estado(eva)).matches.length, 'una respuesta vacía vale como rechazo')
await jugador(beto)
await jugador(caro)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: false })
ok((await mia(ana)).rechazados.includes(beto.id), 'la sala rechaza a un jugador')
await x.rpc(caro, 'enviar_mensaje', { p_a: beto.id })
await x.rpc(beto, 'responder_mensaje', { p_id: (await pedido(beto)).id, p_aceptar: true })
ok(!(await pedido(ana)), 'y no se lo vuelven a acercar escondido en el grupo de otro')

titulo('La app me acercó a una sala y además le escribo')
await limpiar()
await sala(ana, 1)
await jugador(beto)
ok((await pedido(ana))?.auto === true, 'la app acerca al jugador')
await x.rpc(beto, 'enviar_mensaje', { p_a: ana.id })
p = await pedido(ana)
ok(p.auto === false && p.texto === '¿Me sumo a tu sala?' && (await estado(ana)).mensajes.filter((q) => q.estado === 'pendiente').length === 1, 'el pedido pasa a ser su mensaje, sin duplicarse')

titulo('Datos que no pueden colarse')
await limpiar()
await falla('una búsqueda no acepta listas enormes', () => jugador(beto, { p_posicion: Array(50).fill('GK') }))
await x.admin(`update public.profiles set foto_url = 'https://otro-sitio.example/pixel.gif' where id = $1`, [beto.id])
await x.admin(`update public.profiles set foto_url = 'https://proyecto.supabase.co/storage/v1/object/public/avatares/' || id || '/foto.jpg?v=123' where id = $1`, [caro.id])
await jugador(beto); await jugador(caro)
const us = (await estado(dani)).usuarios
ok(us.find((u) => u.id === beto.id).foto === null && us.find((u) => u.id === caro.id).foto === '123' && !('foto_url' in us[0]), 'de las fotos de los demás solo viaja la versión, y solo si es la de su carpeta')
await falla('un nick con saltos de línea no pasa', () => x.sql(beto, `update public.profiles set nick = E'a\n\nb' where id = '${beto.id}'`))

titulo('Sumado que se queda sin grupo')
await limpiar()
await jugador(beto); await jugador(caro)
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
await x.admin(`delete from public.busquedas where user_id = $1`, [beto.id])
bc = await mia(caro)
ok(bc?.estado === 'activa' && bc.lider_id === null, 'si desaparece quien armó el grupo, el sumado vuelve a la cola solo')

console.log(fallas ? `\n${fallas} comprobaciones fallaron.` : '\nTodo bien.')
process.exit(fallas ? 1 : 0)
