// Prueba los SQL de supabase/ en un Postgres local, sin tocar el proyecto real.
// Uso: npm run test:sql
import { readFileSync } from 'node:fs'
import { altaUsuario, crearAcceso, crearBase } from './supabase-local.mjs'

const db = await crearBase()
const x = crearAcceso(db)
let fallas = 0
const ok = (cond, texto) => { console.log(`${cond ? '  ✓' : '  ✗'} ${texto}`); if (!cond) fallas++ }
const falla = async (texto, fn) => {
  try { await fn(); ok(false, `${texto} (tenía que fallar y no falló)`) } catch (e) { ok(true, `${texto} → "${String(e.message).slice(0, 60)}"`) }
}
const titulo = (t) => console.log(`\n${t}`)

// =============================== Perfiles ===================================

const A = { id: '00000000-0000-0000-0000-00000000000a', usuario: 'lauti_hax', nombre: 'Lauti' }
const B = { id: '00000000-0000-0000-0000-00000000000b', usuario: 'pepito', nombre: 'Pepito' }
await x.admin(`insert into auth.users values ($1), ($2)`, [A.id, B.id])

titulo('Perfil')
const a1 = await x.rpc(A, 'mi_perfil')
ok(a1.username === 'lauti_hax' && a1.nick === 'Lauti', 'la primera vez crea el perfil con el usuario y el nombre visible de Discord')
ok(/^HX[A-HJ-NP-Z2-9]{4}$/.test(a1.codigo), `genera un código de referido (${a1.codigo})`)
ok(a1.onboarding === false, 'arranca con el registro sin terminar')
const a2 = await x.rpc({ ...A, usuario: 'otro', nombre: 'Otro' }, 'mi_perfil')
ok(a2.codigo === a1.codigo && a2.nick === 'Lauti', 'volver a entrar no crea otro perfil ni cambia el código')
await falla('un visitante no puede pedir un perfil', () => x.rpc(null, 'mi_perfil'))

titulo('Registro')
await falla('rechaza un nick de un carácter', () => x.rpc(A, 'completar_registro', { p_nick: 'X', p_region: ['ARG'] }))
await falla('rechaza una región que no existe', () => x.rpc(A, 'completar_registro', { p_nick: 'Lauti10', p_region: ['MX'] }))
await falla('rechaza quedarse sin región', () => x.rpc(A, 'completar_registro', { p_nick: 'Lauti10', p_region: [] }))
const a3 = await x.rpc(A, 'completar_registro', { p_nick: 'Lauti10', p_region: ['ARG', 'UY'], p_codigo: a1.codigo })
ok(a3.nick === 'Lauti10' && a3.onboarding === true && a3.region.join() === 'ARG,UY', 'guarda nick y regiones y termina el registro')
ok(a3.referido_por === null, 'no deja usar el código propio')
ok((await x.rpc(A, 'completar_registro', { p_nick: '', p_region: ['ARG'] })).nick === 'lauti_hax', 'sin nick usa el usuario de Discord')

titulo('Código de un amigo')
ok(await x.rpc(null, 'quien_invita', { p_codigo: ` ${a1.codigo.toLowerCase()} ` }) === 'lauti_hax', 'un visitante puede validar un código (sin importar mayúsculas ni espacios)')
ok(await x.rpc(null, 'quien_invita', { p_codigo: 'NOEXISTE' }) === null, 'un código que no existe devuelve vacío')
await x.rpc(B, 'mi_perfil')
const b1 = await x.rpc(B, 'completar_registro', { p_nick: 'Pepito', p_region: ['CHI'], p_codigo: a1.codigo })
ok(b1.referido_por === A.id && b1.invito === 'lauti_hax', 'una cuenta nueva queda anotada como invitada por el dueño del código')
ok((await x.rpc(B, 'completar_registro', { p_nick: 'Pepito', p_region: ['CHI'], p_codigo: 'OTRO99' })).referido_por === A.id, 'una cuenta que ya terminó el registro no puede cambiar quién la invitó')

titulo('Permisos de perfiles')
ok((await x.sql(B, 'select id, username, nick, region, foto_url from public.profiles')).length === 2, 'un usuario ve los datos públicos de los demás')
await falla('no puede leer quién invitó a otro', () => x.sql(B, 'select referido_por from public.profiles'))
await falla('un visitante no puede leer perfiles', () => x.sql(null, 'select nick from public.profiles'))
await x.sql(B, `update public.profiles set nick = 'Hackeado' where id = '${A.id}'`)
ok((await x.rpc(A, 'mi_perfil')).nick === 'lauti_hax', 'no puede cambiar el perfil de otro')
await x.sql(B, `update public.profiles set foto_url = 'https://ejemplo/foto.jpg', nick = 'Pepe' where id = '${B.id}'`)
ok((await x.rpc(B, 'mi_perfil')).nick === 'Pepe', 'sí puede cambiar su foto y su nick')
await falla('no puede cambiarse el código', () => x.sql(B, `update public.profiles set codigo = 'HXAAAA' where id = '${B.id}'`))
await falla('no puede insertar perfiles a mano', () => x.sql(B, `insert into public.profiles (id, username, nick, codigo) values ('${B.id}', 'x', 'xx', 'HX0000')`))

titulo('Fotos')
await x.sql(A, `insert into storage.objects (bucket_id, name) values ('avatares', '${A.id}/foto.jpg')`)
ok(true, 'puede subir una foto a su propia carpeta')
await falla('no puede subir una foto a la carpeta de otro', () => x.sql(B, `insert into storage.objects (bucket_id, name) values ('avatares', '${A.id}/foto.jpg')`))
ok((await x.sql(B, `delete from storage.objects where bucket_id = 'avatares' returning id`)).length === 0, 'no puede borrar la foto de otro')

// ================================= Cola =====================================

const ana = await altaUsuario(x, 1, 'ana')
const beto = await altaUsuario(x, 2, 'beto')
const caro = await altaUsuario(x, 3, 'caro')
const dani = await altaUsuario(x, 4, 'dani')
const eva = await altaUsuario(x, 5, 'eva')
const fran = await altaUsuario(x, 6, 'fran', 'fran', ['CHI'])

const jugador = (u, extra = {}) => x.rpc(u, 'crear_busqueda', { p_modo: 'jugador', p_formato: ['3v3'], p_posicion: ['Polifuncional'], p_cancha: ['Cualquiera'], p_region: ['ARG'], p_duracion: '15min', ...extra })
const sala = (u, faltan, extra = {}) => x.rpc(u, 'crear_busqueda', { p_modo: 'sala', p_formato: null, p_posicion: ['Polifuncional'], p_cancha: ['Cualquiera'], p_region: ['ARG'], p_nombre_sala: `sala de ${u.usuario}`, p_faltan: faltan, ...extra })
const estado = (u) => x.rpc(u, 'estado_cola')
const mia = async (u) => (await estado(u)).busquedas.find((b) => b.user_id === u.id)
const pedido = async (u) => (await estado(u)).mensajes.find((m) => m.a === u.id && m.estado === 'pendiente')
const partido = async (u) => (await estado(u)).matches[0]
const limpiar = async () => {
  for (const u of [ana, beto, caro, dani, eva, fran]) await x.rpc(u, 'cancelar_busqueda')
  await x.admin(`update public.busquedas set estado = 'cancelada' where estado in ('activa', 'agrupada', 'match')`)
  await x.admin(`delete from public.matches`)
  await x.admin(`delete from public.mensajes`)
}

titulo('Búsquedas')
await falla('sin terminar el registro no se puede buscar', async () => {
  const nuevo = { id: '00000000-0000-0000-0000-000000000099', usuario: 'nuevo' }
  await x.admin(`insert into auth.users values ($1)`, [nuevo.id]); await x.rpc(nuevo, 'mi_perfil'); await jugador(nuevo)
})
await jugador(beto)
ok((await mia(beto)).estado === 'activa' && (await mia(beto)).expira_at !== null, 'un jugador se pone disponible por 15 minutos')
await falla('una sola búsqueda activa por usuario', () => sala(beto, 2))
await falla('una sala necesita nombre', () => sala(ana, 2, { p_nombre_sala: '  ' }))
await falla('una sala no puede pedir 8 jugadores', () => sala(ana, 8))
await falla('no acepta una cancha inventada', () => jugador(caro, { p_cancha: ['Cancha rara'] }))
ok((await estado(caro)).busquedas.length === 1 && (await estado(caro)).usuarios.some((u) => u.nick === 'beto'), 'los demás ven la búsqueda y quién la hizo')
await x.rpc(beto, 'cancelar_busqueda')
ok((await estado(caro)).busquedas.length === 0, 'al cancelar desaparece de la cola')
await falla('un visitante no puede ver la cola', () => x.rpc(null, 'estado_cola'))
await falla('nadie puede leer las tablas directo', () => x.sql(beto, 'select * from public.busquedas'))
await falla('nadie puede escribir las tablas directo', () => x.sql(beto, `update public.match_participantes set confirmado_at = now()`))
await falla('la app no puede llamar a las funciones internas', () => x.sql(beto, `select public._ocupar(gen_random_uuid(), array[]::uuid[], 'B')`))
ok((await x.sql(beto, 'select version from public.cambios')).length === 1, 'la señal de cambios sí se puede leer')

titulo('Sala: la app acerca jugadores, el dueño acepta, entra y confirma')
await limpiar()
await sala(ana, 2)
await jugador(beto)
let p = await pedido(ana)
ok(p && p.auto && p.de === beto.id, 'al aparecer un jugador compatible, la app se lo acerca a la sala')
ok(!(await estado(beto)).matches.length, 'hasta que el dueño acepte no hay match')
await falla('solo el dueño de la sala puede responder ese pedido', () => x.rpc(caro, 'responder_mensaje', { p_id: p.id, p_aceptar: true }))
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
let m = await partido(beto)
ok(m && m.creado_por === ana.id && m.nombre_sala === 'sala de ana', 'al aceptar, el jugador recibe el match con el nombre de la sala')
ok((await mia(ana)).faltan === 1 && (await mia(ana)).estado === 'activa', 'la sala sigue buscando: le falta 1')
ok(!(await mia(beto)), 'la búsqueda del jugador se cerró')
await falla('el que entra no puede marcar quién entró', () => x.rpc(beto, 'marcar_entro', { p_user: ana.id }))
await x.rpc(ana, 'marcar_entro', { p_user: beto.id })
m = await partido(ana)
ok(m.contado_at === null && m.participantes.find((q) => q.user_id === beto.id).entro_at !== null, '"Ya entró" queda anotado; el partido todavía no cuenta')
await x.rpc(beto, 'confirmar_match', { p_match: m.id })
ok((await partido(ana)).contado_at !== null, 'cuando confirma el que entró, el partido cuenta')
await falla('uno de afuera no puede confirmar el partido', () => x.rpc(caro, 'confirmar_match', { p_match: m.id }))

titulo('Sala: rechazar y "Se salió"')
await jugador(caro)
p = await pedido(ana)
ok(p && p.de === caro.id, 'con un lugar libre, la app acerca al siguiente')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: false })
ok((await mia(ana)).rechazados.includes(caro.id) && !(await pedido(ana)), 'al rechazarlo, no se lo vuelve a acercar')
ok((await mia(caro)).estado === 'activa', 'el rechazado sigue buscando')
await x.rpc(ana, 'marcar_salio', { p_user: beto.id })
ok((await mia(ana)).faltan === 2, '"Se salió" libera el lugar')
ok((await partido(ana)).contado_at !== null, 'el partido que ya contó no se pierde')
ok((await partido(ana)).participantes.find((q) => q.user_id === beto.id)?.salio_at != null, 'el que se fue deja el lugar, pero sigue figurando en el partido')
ok((await estado(beto)).resumen.jugados === 1 && (await partido(beto))?.contado_at !== null, 'y a él el partido le sigue contando')
await falla('otro usuario no puede sacar gente de una sala ajena', () => x.rpc(caro, 'marcar_salio', { p_user: ana.id, p_match: m.id }))

titulo('Sala completa: se cierra sola cuando entraron todos')
await limpiar()
await sala(ana, 1)
await jugador(beto)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
ok((await mia(ana)).faltan === 0 && (await mia(ana)).completa_at !== null, 'al llenarse queda marcada como completa (reloj quieto)')
await jugador(caro)
ok(!(await pedido(ana)), 'a una sala completa no se le acerca a nadie')
await x.rpc(ana, 'marcar_entro', { p_user: beto.id })
ok(!(await mia(ana)), 'completa y con todos adentro: la búsqueda se cierra')
m = await partido(ana)
await x.rpc(ana, 'marcar_salio', { p_user: beto.id, p_match: m.id })
ok((await mia(ana))?.faltan === 1 && !(await estado(ana)).matches.length, 'si se va antes de que cuente, la sala se reabre y no queda partido')
ok((await pedido(ana))?.de === caro.id, 'y la app vuelve a acercarle gente')

titulo('Mensajes: jugador a sala y sala a jugador')
await limpiar()
await sala(ana, 1, { p_region: ['UY'] })
await jugador(beto)
ok(!(await pedido(ana)), 'sin región en común la app no los acerca')
await x.rpc(beto, 'enviar_mensaje', { p_a: ana.id })
p = await pedido(ana)
ok(p && !p.auto && p.texto === '¿Me sumo a tu sala?', 'pero el jugador puede escribirle igual a la sala')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
ok((await partido(beto))?.creado_por === ana.id, 'si la sala acepta, hay match aunque no fuera lo que buscaba')
await limpiar()
await sala(ana, 2)
await jugador(fran, { p_region: ['CHI'] })
await x.rpc(ana, 'enviar_mensaje', { p_a: fran.id })
p = await pedido(fran)
ok(p?.texto === '¿Te sumás a mi sala?', 'la sala puede invitar a un jugador')
await x.rpc(fran, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
ok((await partido(fran))?.creado_por === ana.id && (await mia(ana)).faltan === 1, 'si el jugador acepta, entra directo (la sala ya lo eligió)')
await falla('no se le puede escribir a alguien que no está buscando', () => x.rpc(beto, 'enviar_mensaje', { p_a: fran.id }))
await falla('no se puede escribir a uno mismo', () => x.rpc(beto, 'enviar_mensaje', { p_a: beto.id }))

titulo('Grupos: el que acepta se suma a la búsqueda y al reloj del otro')
await limpiar()
await jugador(beto, { p_formato: ['4v4'] })
await jugador(caro, { p_formato: ['4v4'] })
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
p = await pedido(caro)
ok(p?.texto === '¿Jugamos un 4v4?', 'un jugador invita a otro')
await x.rpc(caro, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
let bc = await mia(caro)
ok(bc.estado === 'agrupada' && bc.lider_id === (await mia(beto)).id, 'el que acepta queda sumado a la búsqueda del que escribió')
ok(!(await estado(dani)).matches.length && (await mia(beto)).estado === 'activa', 'no hay match: siguen buscando juntos')
await falla('solo quien armó el grupo puede escribirles a otros', () => x.rpc(caro, 'enviar_mensaje', { p_a: dani.id }))
await sala(ana, 1)
ok(!(await pedido(ana)), 'un grupo de 2 no se acerca a una sala a la que le falta 1')
await falla('ni puede escribirle: no entran todos', () => x.rpc(beto, 'enviar_mensaje', { p_a: ana.id }))
await x.rpc(caro, 'cancelar_busqueda')
ok(!(await mia(caro)) && (await mia(beto)).estado === 'activa', 'un sumado puede irse del grupo sin cortar la búsqueda del otro')
ok((await pedido(ana))?.de === beto.id, 'y al quedar solo, la app sí lo acerca a la sala de 1')

titulo('Prioridad: el grupo del tamaño justo le gana a los jugadores sueltos')
await limpiar()
await jugador(dani)
await jugador(beto, { p_formato: ['4v4'] })
await jugador(caro, { p_formato: ['4v4'] })
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
await sala(ana, 2)
p = await pedido(ana)
ok(p?.de === beto.id && p.con.length === 1 && p.con[0] === caro.id, 'a una sala a la que le faltan 2 le llega primero el grupo de 2, aunque el suelto buscaba desde antes')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
m = await partido(caro)
ok(m?.participantes.length === 3 && (await mia(ana)).faltan === 0, 'al aceptar entra el grupo completo y la sala queda llena')
ok(!(await mia(beto)) && !(await mia(caro)), 'la búsqueda de los dos se cerró')
ok((await mia(dani)).estado === 'activa', 'el suelto sigue buscando')
await x.rpc(ana, 'marcar_entro', { p_user: beto.id })
await x.rpc(caro, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).contado_at !== null, 'alcanza con que confirme uno de los que entraron: cuenta para todos')

titulo('Equipo completo: arma sala y busca rival')
await limpiar()
await jugador(beto)
await jugador(caro)
await jugador(dani)
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
ok((await mia(beto)).equipo_listo === false, 'dos buscando 3v3 todavía no son un equipo')
await x.rpc(beto, 'enviar_mensaje', { p_a: dani.id })
await x.rpc(dani, 'responder_mensaje', { p_id: (await pedido(dani)).id, p_aceptar: true })
ok((await mia(beto)).equipo_listo === true, 'tres buscando 3v3 ya son un equipo completo')
await sala(ana, 3)
p = await pedido(ana)
ok(p?.de === beto.id && p.con.length === 2, 'un equipo completo de 3 es justo lo que necesita una sala a la que le faltan 3: la app se lo acerca')
await x.rpc(ana, 'cancelar_busqueda')
ok(!(await pedido(ana)) && (await mia(beto)).equipo_listo, 'si esa sala se va, el equipo sigue completo y puede armar la suya')
await falla('un sumado no puede crear la sala del grupo', () => x.rpc(caro, 'convertir_en_sala', { p_nombre: 'x', p_faltan: 3 }))
await x.rpc(beto, 'convertir_en_sala', { p_nombre: 'equipo beto', p_faltan: 3 })
let sb = await mia(beto)
ok(sb.modo === 'sala' && sb.faltan === 3 && sb.nombre_sala === 'equipo beto', 'quien armó el grupo crea la sala y pasan a buscar 3')
m = await partido(caro)
ok(m.participantes.filter((q) => q.equipo === 'A').length === 3, 'los tres quedan del mismo lado')
await x.rpc(beto, 'marcar_entro', { p_user: caro.id })
await x.rpc(caro, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).contado_at === null, 'entre compañeros no alcanza: falta que confirme un rival')
await jugador(eva)
await x.rpc(beto, 'responder_mensaje', { p_id: (await pedido(beto)).id, p_aceptar: true })
await x.rpc(eva, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).contado_at !== null, 'cuando entra y confirma un rival, el partido cuenta')

titulo('Jugar entre nosotros')
await limpiar()
await jugador(beto, { p_formato: ['Cualquiera'] })
await jugador(caro, { p_formato: ['Cualquiera'] })
await falla('solo no se puede jugar "entre nosotros"', () => x.rpc(beto, 'convertir_en_sala', { p_nombre: 'solo', p_faltan: 0, p_entre_nosotros: true }))
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
ok((await mia(beto)).equipo_listo === false, 'con "Cualquiera" el grupo nunca se completa solo')
await x.rpc(beto, 'convertir_en_sala', { p_nombre: 'mano a mano', p_faltan: 0, p_entre_nosotros: true })
ok((await mia(beto)).faltan === 0, 'la sala queda completa: no busca a nadie más')
m = await partido(caro)
await x.rpc(beto, 'marcar_entro', { p_user: caro.id })
ok(!(await mia(beto)), 'al entrar el otro, la búsqueda se cierra')
await x.rpc(caro, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).contado_at !== null, 'son rivales entre ellos: con los dos confirmando, cuenta')

titulo('Quien arma el grupo cancela, y cartel de los 15 minutos')
await limpiar()
await jugador(beto)
await jugador(caro)
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
await x.rpc(beto, 'cancelar_busqueda')
bc = await mia(caro)
ok(bc.estado === 'activa' && bc.lider_id === null, 'si cancela quien armó el grupo, los sumados vuelven a la cola por su cuenta')
ok(new Date(bc.expira_at) - new Date((await estado(caro)).ahora) > 14 * 60 * 1000, 'y arrancan con 15 minutos nuevos')
await x.admin(`update public.busquedas set expira_at = now() - interval '1 minute' where user_id = $1 and estado = 'activa'`, [caro.id])
ok((await mia(caro))?.estado === 'activa', 'al cumplirse los 15 minutos hay 2 de gracia para responder el cartel')
await x.rpc(caro, 'renovar_busqueda')
ok(new Date((await mia(caro)).expira_at) > new Date(), 'renovar da 15 minutos más')
await x.admin(`update public.busquedas set expira_at = now() - interval '3 minutes' where user_id = $1 and estado = 'activa'`, [caro.id])
ok(!(await mia(caro)), 'pasada la gracia, la búsqueda vence sola')

titulo('Sin señales de vida')
await limpiar()
await jugador(beto, { p_duracion: 'match' })
await sala(ana, 2)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
await jugador(caro, { p_duracion: 'match' })
await x.admin(`update public.busquedas set visto_at = now() - interval '11 minutes' where user_id in ($1, $2)`, [ana.id, caro.id])
const e = await estado(dani)
ok(!e.busquedas.some((b) => b.user_id === caro.id), 'una búsqueda cuyo dueño no aparece hace 10 minutos sale de la cola')
ok(!e.busquedas.some((b) => b.user_id === ana.id) && (await partido(beto)), 'una sala con gente adentro se cierra, pero el partido queda')

titulo('Pendientes')
m = await partido(beto)
await x.rpc(beto, 'descartar_match', { p_match: m.id })
ok((await partido(beto)).participantes.find((q) => q.user_id === beto.id).descarto === true, '"No lo jugué" queda anotado solo para quien lo dijo')
await x.rpc(beto, 'confirmar_match', { p_match: m.id })
ok((await partido(beto)).participantes.find((q) => q.user_id === beto.id).confirmado_at !== null, 'después se puede confirmar igual')
ok((await partido(beto)).contado_at === null, 'pero no cuenta hasta que confirme el otro lado')

titulo('Varias salas, un jugador')
await limpiar()
await sala(ana, 1)
await sala(dani, 1)
await jugador(beto)
ok((await pedido(ana))?.de === beto.id && (await pedido(dani))?.de === beto.id, 'el mismo jugador queda propuesto a las dos salas')
await x.rpc(dani, 'responder_mensaje', { p_id: (await pedido(dani)).id, p_aceptar: true })
ok((await partido(beto))?.creado_por === dani.id && !(await pedido(ana)), 'entra a la primera que lo acepta y el otro pedido se cae')
await falla('la otra sala ya no puede aceptarlo', async () => {
  const viejo = (await estado(ana)).mensajes.find((q) => q.de === beto.id)
  await x.rpc(ana, 'responder_mensaje', { p_id: viejo.id, p_aceptar: true })
})

titulo('Resumen del perfil y reportes')
ok((await estado(dani)).resumen.jugados === 0, 'un partido sin confirmar no cuenta como jugado')
m = await partido(dani)
await x.rpc(dani, 'marcar_entro', { p_user: beto.id })
await x.rpc(beto, 'confirmar_match', { p_match: m.id })
ok((await estado(dani)).resumen.jugados === 1 && (await estado(beto)).resumen.jugados === 1, 'al confirmarse suma un jugado para los dos')
await x.rpc(beto, 'reportar', { p_user: dani.id, p_motivo: 'No apareció', p_detalle: 'nunca entró' })
ok((await x.admin('select * from public.reportes')).length === 1, 'un reporte queda guardado')
await falla('no se puede reportar a uno mismo', () => x.rpc(beto, 'reportar', { p_user: beto.id, p_motivo: 'No apareció' }))
await falla('el motivo tiene que ser uno de la lista', () => x.rpc(beto, 'reportar', { p_user: dani.id, p_motivo: 'Porque sí' }))
await falla('los reportes no se pueden leer desde la app', () => x.sql(beto, 'select * from public.reportes'))

titulo('Nadie ocupa dos lugares en la misma sala')
await limpiar()
await sala(ana, 3)
await jugador(beto)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
await jugador(beto)
ok(!(await pedido(ana)) && (await mia(ana)).faltan === 2, 'si el que ya entró vuelve a buscar, la app no se lo acerca de nuevo a esa sala')
await falla('ni puede escribirle para entrar otra vez', () => x.rpc(beto, 'enviar_mensaje', { p_a: ana.id }))
await falla('ni la sala puede invitarlo de nuevo', () => x.rpc(ana, 'enviar_mensaje', { p_a: beto.id }))
await x.rpc(beto, 'cancelar_busqueda')

titulo('El partido le cuenta a cada uno cuando entró o confirmó')
await x.rpc(ana, 'marcar_entro', { p_user: beto.id })
m = await partido(ana)
await x.rpc(beto, 'confirmar_match', { p_match: m.id })
ok((await partido(ana)).contado_at !== null && (await partido(beto)).contado_at !== null, 'con uno de cada lado, el partido cuenta')
await jugador(caro)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
ok((await partido(caro)).contado_at === null && (await estado(caro)).resumen.jugados === 0, 'al que aceptan después no le cuenta por el solo hecho de estar anotado')
await x.rpc(ana, 'marcar_entro', { p_user: caro.id })
ok((await partido(caro)).contado_at !== null && (await estado(caro)).resumen.jugados === 1, 'le cuenta cuando el dueño marca que entró (o cuando confirma)')
await x.rpc(ana, 'marcar_salio', { p_user: caro.id })
ok((await estado(caro)).resumen.jugados === 1 && (await mia(ana)).faltan === 2, '"Se salió" después de contar libera el lugar sin sacarle el partido')
await jugador(caro)
p = await pedido(ana)
ok(p?.de === caro.id, 'el que se fue puede volver a esa sala')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: true })
ok((await partido(ana)).participantes.find((q) => q.user_id === caro.id).salio_at === null && (await mia(ana)).faltan === 1, 'y vuelve a ocupar un lugar')

titulo('"No vino" y salas cerradas')
await jugador(dani)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
ok((await mia(ana)).faltan === 0, 'la sala se llenó')
await x.rpc(ana, 'marcar_salio', { p_user: dani.id })
ok((await mia(ana)).faltan === 1 && !(await estado(dani)).matches.length, 'al que nunca entró se lo puede sacar: se libera el lugar y a él no le queda nada')
await x.rpc(ana, 'cancelar_busqueda')
ok(!(await mia(ana)) && (await partido(ana)), 'cerrar la sala con gente adentro deja el partido')
await x.rpc(ana, 'marcar_salio', { p_user: caro.id, p_match: (await partido(ana)).id })
ok(!(await mia(ana)), 'una sala que cerró su dueño no se reabre con "Se salió"')

titulo('Mensajes que dejan de tener sentido')
await limpiar()
await falla('sin estar buscando no se puede escribir', async () => { await sala(ana, 2); await x.rpc(dani, 'enviar_mensaje', { p_a: ana.id }) })
await jugador(beto, { p_region: ['CHI'] })
await jugador(caro, { p_region: ['CHI'] })
await x.rpc(beto, 'enviar_mensaje', { p_a: ana.id })
ok((await pedido(ana))?.con.length === 0, 'un jugador solo le escribe a una sala')
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
p = await pedido(ana)
ok(p?.con.length === 1 && p.con[0] === caro.id && p.texto === '¿Entramos 2 a tu sala?', 'si después suma a alguien a su grupo, el pedido se actualiza')
await jugador(dani, { p_region: ['CHI'] })
await x.rpc(beto, 'enviar_mensaje', { p_a: dani.id })
await x.rpc(dani, 'responder_mensaje', { p_id: (await pedido(dani)).id, p_aceptar: true })
ok(!(await pedido(ana)), 'y si ya no entran todos, el pedido se cae solo')
await x.rpc(beto, 'cancelar_busqueda'); await x.rpc(caro, 'cancelar_busqueda'); await x.rpc(dani, 'cancelar_busqueda')
await jugador(eva)
p = await pedido(ana)
ok(p?.auto && p.de === eva.id, 'la sala no quedó trabada: la app le acerca al siguiente')
await x.rpc(ana, 'responder_mensaje', { p_id: p.id, p_aceptar: null })
ok((await mia(ana)).faltan === 2 && !(await estado(eva)).matches.length, 'una respuesta vacía vale como rechazo')
await jugador(beto)
await jugador(caro)
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: false })
ok((await mia(ana)).rechazados.includes(beto.id), 'la sala rechaza a un jugador')
await x.rpc(caro, 'enviar_mensaje', { p_a: beto.id })
await x.rpc(beto, 'responder_mensaje', { p_id: (await pedido(beto)).id, p_aceptar: true })
ok(!(await pedido(ana)), 'y no se lo vuelven a acercar escondido en el grupo de otro')

titulo('La app me acercó a una sala y además le escribo')
await limpiar()
await sala(ana, 1)
await jugador(beto)
ok((await pedido(ana))?.auto === true, 'la app acerca al jugador')
await x.rpc(beto, 'enviar_mensaje', { p_a: ana.id })
p = await pedido(ana)
ok(p.auto === false && p.texto === '¿Me sumo a tu sala?' && (await estado(ana)).mensajes.filter((q) => q.estado === 'pendiente').length === 1, 'el pedido pasa a ser su mensaje, sin duplicarse')

titulo('Datos que no pueden colarse')
await limpiar()
await falla('una búsqueda no acepta listas enormes', () => jugador(beto, { p_posicion: Array(50).fill('GK') }))
await x.admin(`update public.profiles set foto_url = 'https://otro-sitio.example/pixel.gif' where id = $1`, [beto.id])
await x.admin(`update public.profiles set foto_url = 'https://proyecto.supabase.co/storage/v1/object/public/avatares/' || id || '/foto.jpg?v=123' where id = $1`, [caro.id])
await jugador(beto); await jugador(caro)
const us = (await estado(dani)).usuarios
ok(us.find((u) => u.id === beto.id).foto === null && us.find((u) => u.id === caro.id).foto === '123' && !('foto_url' in us[0]), 'de las fotos de los demás solo viaja la versión, y solo si es la de su carpeta')
await falla('un nick con saltos de línea no pasa', () => x.sql(beto, `update public.profiles set nick = E'a\n\nb' where id = '${beto.id}'`))

titulo('Sumado que se queda sin grupo')
await limpiar()
await jugador(beto); await jugador(caro)
await x.rpc(beto, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
await x.admin(`delete from public.busquedas where user_id = $1`, [beto.id])
bc = await mia(caro)
ok(bc?.estado === 'activa' && bc.lider_id === null, 'si desaparece quien armó el grupo, el sumado vuelve a la cola solo')

// ============================ Amigos y avisos ==============================

const est = (u, visible = true) => x.rpc(u, 'estado', { p_visible: visible })
const relacion = async (u, otro) => (await est(u)).amigos.find((q) => q.id === otro.id)?.relacion
const avisos = async () => (await x.admin('select body, headers, url from net.pedidos order by id')).map((r) => ({ ...r.body.aviso, n: r.body.suscripciones.length, secreto: r.headers['x-haxmatch-secreto'], a: r.url }))
const vaciarAvisos = () => x.admin('delete from net.pedidos')
const suscribir = (u, n = 1) => x.rpc(u, 'guardar_suscripcion', { p_endpoint: `https://fcm.googleapis.com/fcm/send/${u.usuario}-${n}`, p_p256dh: 'B'.repeat(87), p_auth: 'a'.repeat(22) })
// Para las pruebas de avisos, nadie tiene la app a la vista.
const nadieMira = () => x.admin('delete from public.presencia')

titulo('Amigos')
await limpiar()
ok((await est(ana)).amigos.length === 0 && Array.isArray((await est(ana)).busquedas), '"estado" devuelve la cola y la lista de amigos')
ok((await x.rpc(ana, 'pedir_amistad', { p_user: beto.id })) === 'enviada', 'se manda una solicitud')
ok((await relacion(ana, beto)) === 'enviada' && (await relacion(beto, ana)) === 'recibida', 'cada uno la ve de su lado')
ok((await x.rpc(ana, 'pedir_amistad', { p_user: beto.id })) === 'enviada', 'mandarla dos veces no duplica')
await falla('no se puede aceptar una solicitud propia', () => x.rpc(ana, 'responder_amistad', { p_user: beto.id, p_aceptar: true }))
await falla('nadie puede aceptarla por otro', () => x.rpc(caro, 'responder_amistad', { p_user: ana.id, p_aceptar: true }))
await x.rpc(beto, 'responder_amistad', { p_user: ana.id, p_aceptar: true })
ok((await relacion(ana, beto)) === 'amigo' && (await relacion(beto, ana)) === 'amigo', 'al aceptar quedan amigos')
ok((await x.rpc(beto, 'pedir_amistad', { p_user: ana.id })) === 'amigos', 'pedirle amistad a un amigo no cambia nada')
await x.rpc(caro, 'pedir_amistad', { p_user: ana.id })
ok((await x.rpc(ana, 'pedir_amistad', { p_user: caro.id })) === 'amigos', 'si los dos se piden amistad, quedan amigos sin aceptar')
const porUsuario = await x.rpc(ana, 'pedir_amistad_por_usuario', { p_username: '@DANI' })
ok(porUsuario.estado === 'enviada' && porUsuario.nick === 'dani', 'se puede agregar por usuario de Discord, con o sin @ y sin importar mayúsculas')
await falla('un usuario que no existe', () => x.rpc(ana, 'pedir_amistad_por_usuario', { p_username: 'nadie_asi' }))
await falla('no se puede agregar a uno mismo', () => x.rpc(ana, 'pedir_amistad', { p_user: ana.id }))
await x.rpc(dani, 'responder_amistad', { p_user: ana.id, p_aceptar: false })
ok(!(await relacion(ana, dani)) && !(await relacion(dani, ana)), 'rechazar borra la solicitud')
await x.rpc(ana, 'quitar_amigo', { p_user: caro.id })
ok(!(await relacion(caro, ana)), 'se puede dejar de ser amigos')
ok(!(await est(eva)).amigos.length, 'los amigos de otros no se ven')
await falla('la tabla de amigos no se puede leer directo', () => x.sql(ana, 'select * from public.amistades'))

titulo('Avisos con la app cerrada')
await falla('una suscripción a un sitio cualquiera no pasa', () => x.rpc(ana, 'guardar_suscripcion', { p_endpoint: 'https://sitio-raro.example/push', p_p256dh: 'B'.repeat(87), p_auth: 'a'.repeat(22) }))
await suscribir(ana); await suscribir(beto); await suscribir(caro)
await vaciarAvisos(); await nadieMira()
await sala(ana, 2)
ok(!(await avisos()).length, 'sin configurar, no sale ningún aviso (y nada se rompe)')
await x.rpc(ana, 'cancelar_busqueda')
await falla('la app no puede configurar los avisos', () => x.rpc(ana, 'configurar_push', { p_url: 'https://malo.example/x', p_secreto: 's'.repeat(40) }))
await falla('la app no puede leer la configuración', () => x.sql(ana, 'select * from public.config_privada'))
await falla('ni las suscripciones de otros', () => x.sql(ana, 'select * from public.push_suscripciones'))
await x.admin(`select public.configurar_push('https://haxmatch.ejemplo.dev/api/push/enviar', $1)`, ['s'.repeat(40)])
await x.admin(`update public.busquedas set creada_at = now() - interval '1 hour' where user_id = $1`, [ana.id])

await vaciarAvisos(); await nadieMira()
await sala(ana, 2)
let av = await avisos()
ok(av.length === 1 && av[0].titulo === 'Tu amigo ana necesita 2 más' && av[0].secreto === 's'.repeat(40) && av[0].a.endsWith('/api/push/enviar'), 'cuando abro una sala, a mi amigo le llega el aviso (y solo a mis amigos)')
await vaciarAvisos(); await nadieMira()
await jugador(caro)
av = await avisos()
ok(av.length === 1 && av[0].titulo === 'caro quiere entrar a tu sala' && av[0].url === '/buscando', 'al dueño le llega el aviso de que alguien quiere entrar a su sala')
await vaciarAvisos(); await nadieMira()
await x.rpc(ana, 'responder_mensaje', { p_id: (await pedido(ana)).id, p_aceptar: true })
av = await avisos()
ok(av.length === 1 && av[0].titulo === 'Match listo con ana' && av[0].url.startsWith('/match/'), 'al aceptarlo, al jugador le llega "Match listo" (y al dueño no: lo acaba de hacer él)')
await vaciarAvisos(); await nadieMira()
await est(ana, true); await est(beto, true)
await jugador(beto)
await x.rpc(ana, 'enviar_mensaje', { p_a: beto.id })
av = await avisos()
ok(av.some((q) => q.titulo === 'beto quiere entrar a tu sala') && av.some((q) => q.titulo === 'ana te escribió'),
  'el aviso se manda aunque la app figure abierta: si de verdad está a la vista, el celular no lo muestra')
// Cancelar y volver a buscar: avisa de nuevo, pero con tope.
for (let i = 0; i < 6; i++) {
  await x.rpc(beto, 'cancelar_busqueda')
  await jugador(beto)
}
av = await avisos()
ok(av.filter((q) => q.titulo === 'beto quiere entrar a tu sala').length === 4, 'si alguien cancela y vuelve a buscar, el dueño recibe hasta 4 avisos suyos en 10 minutos y después se corta')
ok(av.filter((q) => q.titulo.startsWith('Tu amigo beto')).length === 3, 'y a sus amigos les llegan hasta 3 en 10 minutos')
await x.rpc(beto, 'cancelar_busqueda')
await x.admin(`update public.busquedas set creada_at = now() - interval '1 hour' where user_id = $1`, [beto.id])
await x.admin(`update public.mensajes set creado_at = now() - interval '1 hour'`)
await vaciarAvisos()
await jugador(beto)
ok((await avisos()).length === 2, 'pasado un rato, vuelven a llegar')
await x.rpc(beto, 'cancelar_busqueda')
await x.admin(`update public.mensajes set creado_at = now() - interval '1 hour'`)
await limpiar(); await vaciarAvisos(); await nadieMira()
await x.admin(`update public.busquedas set creada_at = now() - interval '1 hour'`)
await jugador(dani); await jugador(caro)
await vaciarAvisos(); await nadieMira()
await x.rpc(dani, 'enviar_mensaje', { p_a: caro.id })
av = await avisos()
ok(av.length === 1 && av[0].titulo === 'dani te escribió' && av[0].cuerpo === '¿Jugamos un 3v3?', 'un mensaje de otro jugador llega como aviso')
await suscribir(dani)
await vaciarAvisos(); await nadieMira()
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
av = await avisos()
ok(av.length === 1 && av[0].titulo === 'caro se sumó a tu búsqueda', 'y cuando acepta, le llega a quien lo invitó')
await vaciarAvisos(); await nadieMira()
await x.rpc(eva, 'pedir_amistad', { p_user: caro.id })
ok((await avisos())[0]?.titulo === 'eva quiere ser tu amigo', 'una solicitud de amistad también avisa')
await suscribir(caro, 2)
await vaciarAvisos(); await nadieMira()
await x.rpc(eva, 'quitar_amigo', { p_user: caro.id }); await x.rpc(eva, 'pedir_amistad', { p_user: caro.id })
ok(!(await avisos()).length && (await relacion(caro, eva)) === 'recibida', 'retirar la solicitud y volver a mandarla no vuelve a avisar (para que nadie insista)')
await nadieMira()
await x.rpc(fran, 'pedir_amistad', { p_user: caro.id })
ok((await avisos())[0]?.n === 2, 'el aviso va a todos los celulares del usuario')
await x.admin(`insert into public.amistad_envios (de, a) select $1, $2 from generate_series(1, 30)`, [fran.id, dani.id])
await falla('hay un tope de solicitudes por hora', () => x.rpc(fran, 'pedir_amistad', { p_user: eva.id }))
await x.admin('delete from public.amistad_envios where de = $1', [fran.id])
await falla('dar de baja una suscripción necesita la clave', () => x.rpc(null, 'baja_suscripcion', { p_endpoint: 'https://fcm.googleapis.com/fcm/send/caro-2', p_secreto: 'no-es' }))
await x.rpc(null, 'baja_suscripcion', { p_endpoint: 'https://fcm.googleapis.com/fcm/send/caro-2', p_secreto: 's'.repeat(40) })
ok((await x.admin(`select 1 from public.push_suscripciones where user_id = $1`, [caro.id])).length === 1, 'con la clave, la web da de baja una suscripción que ya no sirve')
await x.rpc(caro, 'quitar_suscripcion', { p_endpoint: 'https://fcm.googleapis.com/fcm/send/caro-1' })
ok(!(await x.admin(`select 1 from public.push_suscripciones where user_id = $1`, [caro.id])).length, 'y cada uno puede desactivar los suyos')

titulo('Avisos de sala: uno por tanda, y también al que vuelve')
await limpiar(); await x.admin(`update public.busquedas set creada_at = now() - interval '1 hour'`)
await suscribir(eva); await suscribir(dani); await suscribir(caro)
await jugador(dani); await jugador(caro)
await x.rpc(dani, 'enviar_mensaje', { p_a: caro.id })
await x.rpc(caro, 'responder_mensaje', { p_id: (await pedido(caro)).id, p_aceptar: true })
await sala(eva, 2)
await x.rpc(eva, 'enviar_mensaje', { p_a: dani.id }).catch(() => {})
await vaciarAvisos(); await nadieMira()
// El grupo de dos acepta la invitación de la sala: entran los dos de una.
const paraDani = (await est(dani)).mensajes.find((q) => q.a === dani.id && q.estado === 'pendiente')
await nadieMira()
await x.rpc(dani, 'responder_mensaje', { p_id: paraDani.id, p_aceptar: true })
av = await avisos()
const alDueno = av.filter((q) => q.titulo.includes('entrar a tu sala'))
ok(alDueno.length === 1 && /^(caro|dani) y 1 más van a entrar a tu sala$/.test(alDueno[0].titulo), 'cuando entra un grupo de dos, al dueño le llega un solo aviso')
ok(av.filter((q) => q.titulo === 'Match listo con eva').length === 1, 'y al compañero le llega su "Match listo" (al que aceptó no: lo hizo él)')
m = await partido(eva)
await x.rpc(eva, 'marcar_entro', { p_user: dani.id }); await x.rpc(dani, 'confirmar_match', { p_match: m.id })
await x.rpc(eva, 'marcar_salio', { p_user: dani.id })
await x.admin(`update public.busquedas set creada_at = now() - interval '1 hour' where user_id = $1`, [dani.id])
await x.admin(`update public.mensajes set creado_at = now() - interval '1 hour'`)
await jugador(dani)
await vaciarAvisos(); await nadieMira()
await x.rpc(eva, 'responder_mensaje', { p_id: (await pedido(eva)).id, p_aceptar: true })
ok((await avisos()).some((q) => q.titulo === 'Match listo con eva'), 'al que vuelve a una sala por la que ya había pasado también le llega "Match listo"')

titulo('La app en segundo plano sigue preguntando: lo que aparezca en esa consulta también se avisa')
await limpiar(); await x.admin(`update public.busquedas set creada_at = now() - interval '1 hour'`); await x.admin(`update public.mensajes set creado_at = now() - interval '1 hour'`)
await sala(eva, 1)
await jugador(fran, { p_duracion: 'match', p_region: ['CHI'] })
await jugador(caro)
await x.rpc(eva, 'responder_mensaje', { p_id: (await pedido(eva)).id, p_aceptar: false })
// Fran no es compatible; se le vence la búsqueda a alguien y la consulta de Eva (oculta) dispara el emparejamiento.
await x.admin(`update public.busquedas set region = array['ARG'] where user_id = $1`, [fran.id])
await x.admin(`update public.busquedas set visto_at = now() - interval '2 hours' where user_id = $1`, [caro.id])
await vaciarAvisos(); await nadieMira()
await est(eva, false)
ok((await avisos()).some((q) => q.titulo === 'fran quiere entrar a tu sala'), 'el pedido que nace de su propia consulta en segundo plano le llega como aviso')

titulo('Aviso de prueba')
await vaciarAvisos()
await est(dani, true)
ok((await x.rpc(dani, 'probar_aviso')) === 'enviado' && (await avisos())[0]?.titulo === 'Aviso de prueba', 'me manda un aviso a mí mismo aunque tenga la app abierta')
await falla('no se puede pedir uno atrás del otro', () => x.rpc(dani, 'probar_aviso'))
ok((await x.rpc(dani, 'resultado_prueba')).estado === 'esperando', 'mientras la web no contesta, el resultado dice que está esperando')
const idPrueba = (await x.admin('select prueba_id from public.presencia where user_id = $1', [dani.id]))[0].prueba_id
await x.admin(`insert into net._http_response (id, status_code, content) values ($1, 200, '{"enviados":1,"resultados":[201]}')`, [idPrueba])
let rp = await x.rpc(dani, 'resultado_prueba')
ok(rp.estado === 'respondio' && rp.codigo === 200 && rp.enviados === 1, 'cuando contesta, dice si el aviso salió hacia el celular')
await x.admin(`update net._http_response set status_code = 401, content = '{"error":"No autorizado"}' where id = $1`, [idPrueba])
rp = await x.rpc(dani, 'resultado_prueba')
ok(rp.codigo === 401 && rp.enviados === null, 'y si la clave no coincide, se ve el rechazo')
ok((await x.rpc(fran, 'resultado_prueba')).estado === 'sin prueba', 'cada uno ve solo su prueba')
await falla('sin celulares con avisos, lo dice', () => x.rpc(fran, 'probar_aviso'))
await falla('un visitante no puede', () => x.rpc(null, 'probar_aviso'))

titulo('Con avisos activados, la búsqueda aguanta más tiempo en segundo plano')
await limpiar()
await jugador(dani, { p_duracion: 'match' }); await jugador(fran, { p_duracion: 'match', p_region: ['CHI'] })
await x.admin(`update public.busquedas set visto_at = now() - interval '15 minutes' where estado = 'activa'`)
let quienes = (await est(eva)).busquedas.map((b) => b.user_id)
ok(quienes.includes(dani.id) && !quienes.includes(fran.id), 'a los 15 minutos sin señales sigue el que tiene avisos y sale el que no')
await x.admin(`update public.busquedas set visto_at = now() - interval '31 minutes' where estado = 'activa'`)
ok(!(await est(eva)).busquedas.length, 'a los 30 minutos sale también')
await db.exec(readFileSync('supabase/02_cola.sql', 'utf8'))
ok((await x.admin(`select public._aguante($1) = interval '30 minutes' as r`, [dani.id]))[0].r, 'volver a ejecutar el paso 2 no deshace lo del paso 3')

// ================================= Clips ====================================

const CLAVE = 's'.repeat(40)
const web = (fn, args) => x.rpc(null, fn, { p_secreto: CLAVE, ...args })
const clips = (u) => x.rpc(u, 'clips')
const video = (id, descripcion, extra = {}) => ({ id: String(id), titulo: '', descripcion, duracion: 20, creado: Math.floor(Date.now() / 1000) - 3600, enlace: `https://www.tiktok.com/@alguien/video/${id}`, ...extra })
const guardar = (state, open, extra = {}) => web('tiktok_guardar', { p_state: state, p_open_id: open, p_nombre: 'Ana TikTok', p_access: 'acc-' + open, p_refresh: 'ref-' + open, p_expira: 86400, p_refresh_expira: 31536000, p_scope: 'user.info.basic,video.list', ...extra })

titulo('Clips: vincular TikTok')
await limpiar(); await vaciarAvisos()
ok((await clips(ana)).tiktok === null && (await clips(ana)).feed.length === 0, 'sin vincular, no hay TikTok ni clips')
await falla('empezar una vinculación necesita la clave', () => x.rpc(null, 'tiktok_empezar', { p_secreto: 'x'.repeat(40), p_user: ana.id }))
await falla('la app no puede leer las llaves de TikTok', () => x.sql(ana, 'select * from public.tiktok_cuentas'))
await falla('ni los videos directo', () => x.sql(ana, 'select * from public.reels'))
let st = await web('tiktok_empezar', { p_user: ana.id })
ok(/^[0-9a-f]{64}$/.test(st), 'la web pide un código de vinculación para el usuario')
await falla('guardar las llaves necesita la clave', () => x.rpc(null, 'tiktok_guardar', { p_secreto: 'no', p_state: st, p_open_id: 'o1', p_nombre: 'x', p_access: 'a', p_refresh: 'r', p_expira: 1, p_refresh_expira: 1, p_scope: '' }))
await falla('un código inventado no sirve', () => guardar('f'.repeat(64), 'open-ana'))
ok((await guardar(st, 'open-ana')) === ana.id, 'con el código correcto, las llaves quedan a nombre de quien empezó')
await falla('el código sirve una sola vez', () => guardar(st, 'open-ana'))
let c = await clips(ana)
ok(c.tiktok.vinculada && c.tiktok.nombre === 'Ana TikTok' && !('access_token' in c.tiktok), 'la app ve que está vinculada, pero nunca las llaves')
st = await web('tiktok_empezar', { p_user: beto.id })
await falla('una cuenta de TikTok no puede estar en dos usuarios', () => guardar(st, 'open-ana'))

titulo('Clips: importar videos')
await falla('importar necesita la clave', () => x.rpc(null, 'tiktok_importar', { p_secreto: 'no', p_user: ana.id, p_videos: [] }))
ok((await web('tiktok_importar', { p_user: ana.id, p_inicial: true, p_completa: true, p_videos: [
  video(7000000001, 'Golazo desde mitad de cancha #HaxBall #golazo', { portada: 'https://p16.tiktokcdn.com/img/1.jpeg?x-expires=1&sig=a_b' }),
  video(7000000002, 'Atajadas de la semana #haxmatch', { creado: Math.floor(Date.now() / 1000) - 60, portada: 'javascript:alert(1)' }),
  video(7000000003, 'Cumple de mi hermana'),
  { id: 'no-es-un-id', descripcion: 'x' },
] })) === 3, 'se guardan los videos válidos y se ignora lo que no es un video')
c = await clips(ana)
ok(c.mios.length === 3 && c.mios.every((r) => r.inicial), 'en Mis videos están todos, marcados como de la primera importación')
ok(c.feed.length === 2 && c.feed[0].tiktok_id === '7000000002' && c.feed[0].nick === 'ana', 'en Clips solo los que tienen #haxball o #haxmatch, del más nuevo al más viejo, con su autor')
ok(c.feed[1].hashtags.includes('haxball') && c.feed[1].titulo.startsWith('Golazo'), 'el hashtag vale aunque esté en mayúsculas, y el título sale de la descripción')
ok(c.feed[1].portada === 'https://p16.tiktokcdn.com/img/1.jpeg?x-expires=1&sig=a_b' && c.mios.find((r) => r.tiktok_id === '7000000001').portada === c.feed[1].portada, 'cada video guarda su miniatura')
ok(c.feed[0].portada === null, 'una miniatura que no es una dirección https se descarta')
await web('tiktok_importar', { p_user: ana.id, p_videos: [video(7000000001, 'Golazo desde mitad de cancha #HaxBall #golazo', { portada: 'https://p16.tiktokcdn.com/img/1-nueva.jpeg' })] })
await web('tiktok_importar', { p_user: ana.id, p_videos: [video(7000000001, 'Golazo desde mitad de cancha #HaxBall #golazo')] })
ok((await clips(ana)).feed[1].portada === 'https://p16.tiktokcdn.com/img/1-nueva.jpeg', 'la miniatura se renueva al volver a traer la lista, y no se pierde si una vez no viene')
ok((await clips(beto)).feed.length === 2 && (await clips(beto)).mios.length === 0, 'los demás ven el feed, no la biblioteca de otro')
await x.rpc(ana, 'reel_visible', { p_reel: c.feed[0].id, p_visible: false })
ok((await clips(beto)).feed.length === 1 && (await clips(ana)).mios.find((r) => r.tiktok_id === '7000000002').visible === false, 'el dueño puede ocultar un video de Clips')
await falla('nadie puede ocultar el video de otro', () => x.rpc(beto, 'reel_visible', { p_reel: c.feed[1].id, p_visible: false }))
await x.rpc(ana, 'reel_visible', { p_reel: c.feed[0].id, p_visible: true })
await web('tiktok_importar', { p_user: ana.id, p_completa: false, p_videos: [video(7000000004, 'Nuevo clip #haxmatch', { creado: Math.floor(Date.now() / 1000) })] })
c = await clips(ana)
ok(c.mios.length === 4 && c.mios.find((r) => r.tiktok_id === '7000000004').inicial === false, 'un video nuevo se suma y no cuenta como de la primera importación')
await web('tiktok_importar', { p_user: ana.id, p_completa: true, p_videos: [video(7000000001, 'Golazo editado #haxball'), video(7000000004, 'Nuevo clip #haxmatch')] })
c = await clips(ana)
ok(c.mios.length === 2 && c.mios.some((r) => r.titulo === 'Golazo editado #haxball'), 'con la lista completa, los que se borraron en TikTok se van y los editados se actualizan')
st = await web('tiktok_empezar', { p_user: beto.id }); await guardar(st, 'open-beto')
await web('tiktok_importar', { p_user: beto.id, p_videos: [video(7000000001, 'me lo quiero quedar #haxball')] })
ok((await clips(beto)).mios.length === 0 && (await clips(ana)).mios.some((r) => r.titulo.startsWith('Golazo editado')), 'un usuario no puede quedarse con el video de otro')

titulo('Clips: reacciones')
const reel = (await clips(beto)).feed[0]
ok((await x.rpc(beto, 'reaccionar', { p_reel: reel.id, p_marcar: true })) === true, 'reaccionar a un clip')
await x.rpc(beto, 'reaccionar', { p_reel: reel.id, p_marcar: true })
c = await clips(beto)
ok(c.feed[0].reacciones === 1 && c.feed[0].reaccione === true && (await clips(caro)).feed[0].reaccione === false, 'se cuenta una sola vez aunque se mande dos veces, y cada uno ve si reaccionó él')
ok((await x.rpc(beto, 'reaccionar', { p_reel: reel.id, p_marcar: false })) === false && (await clips(beto)).feed[0].reacciones === 0, 'se puede quitar')
await falla('no se puede reaccionar a un clip que no existe', () => x.rpc(beto, 'reaccionar', { p_reel: '00000000-0000-0000-0000-00000000dead', p_marcar: true }))

titulo('Clips: actualizar, llaves vencidas y desvincular')
await vaciarAvisos()
ok((await x.rpc(ana, 'tiktok_actualizar')) === 'pedido', 'el usuario puede pedir que se actualicen sus videos')
let pedidos = await x.admin(`select url, body from net.pedidos order by id`)
ok(pedidos.length === 1 && pedidos[0].url.endsWith('/api/tiktok/sincronizar') && pedidos[0].body.access_token === 'acc-open-ana' && pedidos[0].body.user_id === ana.id, 'la base le manda a la web las llaves de ese usuario para que traiga sus videos')
ok((await x.rpc(ana, 'tiktok_actualizar')) === 'reciente' && (await x.admin('select 1 from net.pedidos')).length === 1, 'pero no una vez atrás de la otra')
await falla('sin TikTok vinculado no hay nada que actualizar', () => x.rpc(caro, 'tiktok_actualizar'))
await falla('guardar llaves renovadas necesita la clave', () => x.rpc(null, 'tiktok_llaves', { p_secreto: 'no', p_user: ana.id, p_tokens: { access_token: 'robada' } }))
await web('tiktok_llaves', { p_user: ana.id, p_tokens: { access_token: 'acc-nueva', refresh_token: 'ref-nueva', expira: 86400, refresh_expira: 0 } })
let cuenta = (await x.admin(`select access_token, refresh_token, refresh_expira_at > now() + interval '300 days' as vigente from public.tiktok_cuentas where user_id = $1`, [ana.id]))[0]
ok(cuenta.access_token === 'acc-nueva' && cuenta.refresh_token === 'ref-nueva' && cuenta.vigente, 'si la web renovó las llaves, quedan guardadas (y un vencimiento vacío no pisa el que había)')
await falla('una lista vacía de verdad no es lo mismo que "no vino nada"', () => web('tiktok_importar', { p_user: ana.id, p_videos: null, p_completa: true }))
ok((await clips(ana)).mios.length === 2, 'y los videos siguen ahí')
await x.admin(`update public.tiktok_cuentas set refresh_expira_at = now() - interval '1 day', pedida_at = null where user_id = $1`, [ana.id])
ok((await x.rpc(ana, 'tiktok_actualizar')) === 'vencido' && /Volvé a vincular/.test((await clips(ana)).tiktok.error), 'si el permiso venció (un año sin usarse), la app pide volver a vincular')
await x.admin(`update public.tiktok_cuentas set refresh_expira_at = now() + interval '300 days', pedida_at = null, error = null where user_id = $1`, [ana.id])
await web('tiktok_fallo', { p_user: ana.id, p_error: 'Hay que volver a vincular TikTok' })
ok((await clips(ana)).tiktok.error === 'Hay que volver a vincular TikTok', 'si TikTok rechaza el acceso, la app se entera')
await x.admin(`update public.tiktok_cuentas set sincronizada_at = now() - interval '7 hours', pedida_at = null, error = null`)
await vaciarAvisos()
ok((await x.admin('select public._tiktok_sincronizar_todos() as n'))[0].n === 2, 'la tarea programada pide actualizar las cuentas que hace rato no se revisan')
// Deslizar para actualizar en Clips.
await vaciarAvisos()
await x.admin(`update public.tiktok_cuentas set sincronizada_at = now() - interval '10 minutes', pedida_at = null, error = null`)
ok((await x.rpc(caro, 'clips_refrescar')) === 2 && (await x.admin('select 1 from net.pedidos')).length === 2, 'deslizar para actualizar pide los videos nuevos de las cuentas vinculadas, aunque quien desliza no tenga TikTok')
ok((await x.rpc(caro, 'clips_refrescar')) === 0, 'y no vuelve a pedirlos enseguida')
await x.admin(`update public.tiktok_cuentas set sincronizada_at = now(), pedida_at = now() - interval '1 minute'`)
await vaciarAvisos()
pedidos = (await x.rpc(ana, 'clips_refrescar')) === 1 ? await x.admin(`select body from net.pedidos`) : []
ok(pedidos.length === 1 && pedidos[0].body.user_id === ana.id, 'la cuenta de quien desliza se pide siempre; las demás, solo si hace rato que no se revisan')
await x.admin(`update public.tiktok_cuentas set sincronizada_at = now() - interval '10 minutes', pedida_at = null, error = 'Hay que volver a vincular TikTok' where user_id = $1`, [ana.id])
await x.admin(`update public.tiktok_cuentas set sincronizada_at = now() where user_id <> $1`, [ana.id])
ok((await x.rpc(ana, 'clips_refrescar')) === 0, 'una cuenta que hay que volver a vincular no se pide')
await x.admin(`update public.tiktok_cuentas set error = null, pedida_at = null where user_id = $1`, [ana.id])
await falla('deslizar para actualizar necesita sesión', () => x.rpc(null, 'clips_refrescar'))
await vaciarAvisos()
await x.rpc(ana, 'tiktok_desvincular')
c = await clips(ana)
pedidos = await x.admin(`select url, body from net.pedidos order by id`)
ok(c.tiktok === null && c.mios.length === 0 && !(await clips(beto)).feed.some((r) => r.user_id === ana.id), 'al desvincular se borran las llaves y todos sus videos')
ok(pedidos.length === 1 && pedidos[0].url.endsWith('/api/tiktok/revocar') && pedidos[0].body.access_token === 'acc-nueva' && pedidos[0].body.refresh_token === 'ref-nueva', 'y se le pide a TikTok que anule el permiso')
st = await web('tiktok_empezar', { p_user: ana.id }); await guardar(st, 'open-ana')
ok((await clips(ana)).tiktok.vinculada, 'después se puede volver a vincular')
await web('tiktok_importar', { p_user: ana.id, p_videos: [video(7000000009, 'viejo #haxball')] })
ok((await clips(ana)).mios[0].inicial === true, 'lo primero que se trae después de vincular cuenta como importación inicial, aunque llegue más tarde')

titulo('Clips: sin la clave configurada, nadie de afuera puede hacer nada')
const guardada = await x.admin('select clave, valor from public.config_privada')
await x.admin('delete from public.config_privada')
const larga = 'x'.repeat(40)
await falla('empezar una vinculación a nombre de otro', () => x.rpc(null, 'tiktok_empezar', { p_secreto: larga, p_user: caro.id }))
await falla('meter videos en la cuenta de otro', () => x.rpc(null, 'tiktok_importar', { p_secreto: larga, p_user: ana.id, p_videos: [video(7000000099, 'spam #haxball')], p_completa: true }))
await falla('pisar las llaves de otro', () => x.rpc(null, 'tiktok_llaves', { p_secreto: larga, p_user: ana.id, p_tokens: { access_token: 'robada' } }))
await falla('marcar la cuenta de otro como caída', () => x.rpc(null, 'tiktok_fallo', { p_secreto: larga, p_user: ana.id, p_error: 'x' }))
await falla('guardar llaves', () => x.rpc(null, 'tiktok_guardar', { p_secreto: larga, p_state: 'a'.repeat(64), p_open_id: 'o', p_nombre: 'n', p_access: 'a', p_refresh: 'r', p_expira: 1, p_refresh_expira: 1, p_scope: '' }))
await falla('dar de baja los avisos de alguien', () => x.rpc(null, 'baja_suscripcion', { p_endpoint: 'https://fcm.googleapis.com/fcm/send/x', p_secreto: larga }))
ok((await clips(ana)).mios.length === 1 && !(await clips(ana)).mios.some((r) => r.titulo.includes('spam')), 'y no cambió nada')
for (const f of guardada) await x.admin('insert into public.config_privada (clave, valor) values ($1, $2)', [f.clave, f.valor])

console.log(fallas ? `\n${fallas} comprobaciones fallaron.` : '\nTodo bien.')
process.exit(fallas ? 1 : 0)
