// Recorrido de humo: abre la app en modo demostración (sin servidor), pasa por los
// flujos principales y guarda capturas a 390 x 844.
// Uso: npm run probar   (en otra terminal)   y después   node scripts/recorrido.mjs [carpeta]
import { chromium } from 'playwright'

const URL = process.env.APP_URL ?? 'http://localhost:4173'
const dir = process.argv[2] ?? 'capturas'
const browser = await chromium.launch(process.env.PW_CHROMIUM ? { executablePath: process.env.PW_CHROMIUM } : {})
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })
const page = await ctx.newPage()
const errores = []
page.on('console', (m) => { if (m.type() === 'error') errores.push(m.text()) })
page.on('pageerror', (e) => errores.push(String(e)))

let n = 0
const foto = async (nombre) => page.screenshot({ path: `${dir}/${String(++n).padStart(2, '0')}-${nombre}.png` })
const boton = (texto) => page.getByRole('button', { name: texto, exact: true })
const link = (texto) => page.getByRole('link', { name: texto, exact: true })
const ver = async (texto, timeout = 12000) => page.getByText(texto, { exact: false }).first().waitFor({ timeout })
const noVer = async (texto) => { if (await page.getByText(texto, { exact: false }).count()) throw new Error(`No debería verse: ${texto}`) }
const fila = (nombre) => page.locator('.card--row', { hasText: nombre })
const tab = (t) => page.locator('.tabbar a', { hasText: t })
const abajo = () => page.locator('.scroll').evaluate((el) => el.scrollTo(0, el.scrollHeight))
const nivel = async () => console.log('  nivel:', await page.locator('.nivel > .m.num').first().innerText())
const paso = (t) => console.log('·', t)
const entrar = async (nick) => {
  await boton('Entrar con Discord').click()
  await ver('Bienvenido')
  if (nick) await page.getByLabel('Tu nick (opcional)').fill(nick)
  await boton('Empezar').click()
  await ver('Quiero jugar un amistoso')
}
const buscarPartido = async () => {
  await boton('Quiero jugar un amistoso').click()
  await ver('Jugadores buscando partidos')
}

await page.goto(URL)
await ver('Entrar con Discord'); await foto('ingresar')

paso('onboarding con nick')
await boton('Registrarme con el código de un amigo').click()
await boton('Continuar').click()
await ver('Escribí el código de tu amigo')
await page.getByLabel('Código de un amigo').fill('noexiste')
await boton('Continuar').click()
await ver('No encontramos ese código'); await foto('ingresar-codigo')
await boton('Volver').click()
await boton('Entrar con Discord').waitFor()
await boton('Registrarme con el código de un amigo').click()
await page.getByLabel('Código de un amigo').fill('nico23')
await boton('Continuar').click()
await ver('Bienvenido'); await ver('te invitó Nico')
for (const p of ['ARG', 'CHI', 'BR', 'UY']) await boton(p).waitFor()
if (await page.getByRole('heading', { name: 'Posición' }).count()) throw new Error('El registro no debería tener la sección Posición')
if (await page.getByLabel('Código de un amigo').count()) throw new Error('El registro no debería pedir el código de un amigo')
if (await boton('GK').count()) throw new Error('El registro no debería pedir posición')
await page.getByLabel('Tu nick (opcional)').fill('X')
await boton('Empezar').click()
await ver('El nick tiene que tener entre 2 y 20 caracteres')
await page.getByLabel('Tu nick (opcional)').fill('ElDemo')
await boton('UY').click()
await foto('onboarding')
await boton('Empezar').click()
await ver('Quiero jugar un amistoso'); await foto('inicio')
await tab('Perfil').click()
await ver('Conectado como Jugador_Demo'); await ver('ElDemo'); await ver('Perfil público · ARG, UY')

paso('foto de perfil: elegir de la galería, encuadrar y guardar')
const galeria = page.locator('.foto input')
if ((await galeria.getAttribute('accept')) !== 'image/*' || (await galeria.getAttribute('capture')) !== null) throw new Error('El selector de foto tiene que abrir la galería')
await galeria.setInputFiles({ name: 'nota.txt', mimeType: 'text/plain', buffer: Buffer.from('hola') })
await ver('Elegí una imagen')
await galeria.setInputFiles({ name: 'rota.png', mimeType: 'image/png', buffer: Buffer.from('esto no es una imagen') })
await ver('No pudimos leer esa imagen')
// Imagen ancha de prueba: mitad izquierda roja, mitad derecha azul.
const ancha = Buffer.from(await page.evaluate(() => {
  const c = document.createElement('canvas'); c.width = 800; c.height = 400
  const x = c.getContext('2d'); x.fillStyle = '#ff0000'; x.fillRect(0, 0, 400, 400); x.fillStyle = '#0000ff'; x.fillRect(400, 0, 400, 400)
  return c.toDataURL('image/png').split(',')[1]
}), 'base64')
const elegir = () => galeria.setInputFiles({ name: 'ancha.png', mimeType: 'image/png', buffer: ancha })
// Color de la foto guardada en una columna (0 a 255), a media altura.
const color = (x) => page.locator('.foto img').evaluate((img, col) => {
  const c = document.createElement('canvas'); c.width = img.naturalWidth; c.height = img.naturalHeight
  const g = c.getContext('2d'); g.drawImage(img, 0, 0)
  const [r, , b] = g.getImageData(col, 128, 1, 1).data
  return r > 180 && b < 80 ? 'rojo' : b > 180 && r < 80 ? 'azul' : `otro(${r},${b})`
}, x)
const medida = () => page.locator('.foto img').evaluate((img) => `${img.naturalWidth}x${img.naturalHeight}`)

await elegir()
await ver('Ajustar foto'); await page.waitForTimeout(300); await foto('ajustar-foto')
await boton('Cancelar').click()
if (await page.locator('.foto img').count()) throw new Error('Cancelar no debería guardar la foto')

await elegir()
await ver('Ajustar foto')
await boton('Guardar foto').click()
await page.locator('.foto img').waitFor()
if (await medida() !== '256x256') throw new Error(`La foto debería quedar de 256x256 y quedó de ${await medida()}`)
if (await color(20) !== 'rojo' || await color(235) !== 'azul') throw new Error(`Sin mover, el recorte tiene que ser el centro: ${await color(20)} / ${await color(235)}`)

await elegir()
await ver('Ajustar foto')
const visor = await page.locator('.recorte__visor').boundingBox()
await page.mouse.move(visor.x + 140, visor.y + 140); await page.mouse.down()
await page.mouse.move(visor.x + 600, visor.y + 140, { steps: 8 }); await page.mouse.up()
await boton('Guardar foto').click()
await page.waitForTimeout(200)
if (await color(20) !== 'rojo' || await color(235) !== 'rojo') throw new Error(`Arrastrando a la derecha tiene que quedar el lado izquierdo: ${await color(20)} / ${await color(235)}`)

await elegir()
await ver('Ajustar foto')
await page.getByRole('slider', { name: 'Zoom' }).fill('3')
await page.mouse.move(visor.x + 140, visor.y + 140); await page.mouse.down()
await page.mouse.move(visor.x - 900, visor.y + 140, { steps: 8 }); await page.mouse.up()
await page.waitForTimeout(200); await foto('ajustar-foto-zoom')
await boton('Guardar foto').click()
await page.waitForTimeout(200)
if (await medida() !== '256x256') throw new Error('Con zoom la foto tiene que seguir siendo de 256x256')
if (await color(20) !== 'azul' || await color(235) !== 'azul') throw new Error(`Con zoom y arrastrando a la izquierda tiene que quedar el lado derecho: ${await color(20)} / ${await color(235)}`)
await ver('Tocá tu foto para cambiarla'); await foto('perfil-con-foto')
await page.reload()
await page.locator('.foto img').waitFor()
await boton('Quitar foto').click()
if (await page.locator('.foto img').count()) throw new Error('La foto no se quitó')
await galeria.setInputFiles('public/icon-512.png')
await boton('Guardar foto').click()
await page.locator('.foto img').waitFor()

paso('tocar dos veces Inicio no cierra la sesión')
await tab('Inicio').dblclick()
await page.waitForTimeout(400)
await ver('Quiero jugar un amistoso'); await noVer('Entrar con Discord'); await noVer('¿Cerrar sesión?')
// Cerrar sesión está en el Perfil, abajo de todo, y pide confirmación.
if (await boton('Cerrar sesión').count()) throw new Error('Cerrar sesión no va en el Inicio')
await tab('Perfil').click()
await boton('Cerrar sesión').click()
await ver('¿Cerrar sesión?'); await page.waitForTimeout(400); await foto('cerrar-sesion')
await boton('Cancelar').click()
await noVer('¿Cerrar sesión?')
await tab('Inicio').click()
await ver('Hola, ElDemo')

paso('quiero jugar: un toque y a la cola, sin formulario ni preguntas')
await boton('Quiero jugar un amistoso').click()
await ver('Buscando partido'); await ver('Región: ARG, UY'); await ver('de 15:00')
await noVer('Modalidad'); await noVer('¿Te avisamos?')
await ver('Jugadores buscando partidos'); await ver('Salas buscando jugadores')
await ver('sala "futsal rolo" · falta 1 · Futsal, Real Futsal'); await ver('sala "nico 3v3 amistoso" · faltan 2 · GK/DFC · Big')
await ver('Tobi_GK +1'); await ver('Grupo de 2'); await foto('buscando')

paso('tocar a un jugador de la cola abre su perfil: amistosos jugados, nivel y agregar a amigos')
await page.getByRole('button', { name: 'Ver a Pibe9' }).click()
await page.getByRole('dialog', { name: 'Perfil de Pibe9' }).waitFor()
await ver('amistosos jugados'); await boton('Agregar a amigos').waitFor()
if ((await page.locator('.ficha .stat .h').allInnerTexts()).join() !== '23,3') throw new Error('El perfil de Pibe9 tendría que decir 23 amistosos y nivel 3')
await page.waitForTimeout(400); await foto('perfil-de-otro')
await boton('Cerrar').click()

paso('jugador rechaza / jugador se suma a mi búsqueda')
await fila('Pibe9').getByRole('button', { name: 'Mensaje' }).click()
await ver('Pibe9 no puede ahora')
await fila('Mati_').getByRole('button', { name: 'Mensaje' }).click()
await ver('Mati_ se sumó a tu búsqueda'); await ver('Buscan con vos')
await ver('Le falta 1 y ustedes son 2')
await abajo(); await page.waitForTimeout(300); await foto('buscando-en-grupo')

paso('una sala invita al grupo: llega la invitación y, al aceptar, entran los dos')
// Mirando la app, la pestaña no titila. En otra ventana, sí, hasta que se vuelve.
const titulo = () => page.title()
const icono = () => page.evaluate(() => document.querySelector('link[rel="icon"]').getAttribute('href'))
await page.evaluate(() => { document.hasFocus = () => false })
await boton('Simular que una sala te invita').click()
await ver('Te invitan a jugar'); await ver('"nico 3v3 amistoso" está necesitando un GK/DFC en la cancha Big. ¿Querés jugar?')
const vistos = new Set()
const iconos = new Set()
for (let i = 0; i < 6; i++) { vistos.add(await titulo()); iconos.add(await icono()); await page.waitForTimeout(450) }
if (![...vistos].every((t) => /^(🟡|⚪) Nico te invita a su sala$/.test(t)) || vistos.size !== 2) throw new Error(`La pestaña no titila: ${[...vistos].join(' | ')}`)
if (iconos.size !== 2 || !iconos.has('/icon.svg')) throw new Error('El ícono de la pestaña no cambia')
await page.evaluate(() => { delete document.hasFocus; window.dispatchEvent(new Event('focus')) })
await page.waitForTimeout(1200)
if ((await titulo()) !== 'HaxMatch' || (await icono()) !== '/icon.svg') throw new Error(`Al volver a la app, la pestaña sigue titilando: ${await titulo()}`)
await ver('Si aceptás, entran los 2 del grupo'); await page.waitForTimeout(400); await foto('invitacion-de-sala')
await boton('Sí, quiero jugar').click()
await ver('No te olvides'); await boton('Entendido').click()
await ver('Sala de Nico'); await ver('Entra con vos'); await noVer('Abrir HaxBall'); await foto('match-listo')
await boton('Ya entré a la sala').click()
await ver('Partido válido · +10 puntos')
await link('Volver al inicio').click()

paso('clips, perfil y pendientes')
await tab('Clips').click()
await ver('Golazo desde mitad de cancha')
while (await page.getByRole('button', { name: 'Reaccionar', exact: true }).count()) await page.getByRole('button', { name: 'Reaccionar', exact: true }).first().click()
await link('Vincular TikTok').click()
await boton('Vincular TikTok').click()
await boton('Simular un video nuevo con #haxmatch').click()
await ver('+8 puntos')
await page.locator('.tabbar a', { hasText: 'Clips' }).click()
await page.locator('.reel__info .av img').first().waitFor(); await foto('clips-con-mi-foto')
await tab('Perfil').click()
await ver('Por confirmar (1)')
await boton('Sí, jugué').click()
await ver('Amistoso confirmado · +10 puntos')
await page.getByRole('link', { name: /Nivel \d+\. Ver detalle/ }).click()
await ver('Qué suma'); await nivel()
await boton('Volver').click()

paso('chat general: leer, escribir, borrar lo propio, moderar y abrir un perfil; puntito de conectado')
// Puntito rojo en la solapa: hay mensajes de otros que todavía no vi. Al entrar, se van.
if (!(await tab('Chat').locator('.dot').count())) throw new Error('La solapa Chat tiene que marcar que hay mensajes sin leer')
await tab('Chat').click()
await ver('Los mensajes duran 24 horas'); await ver('armé sala "nico 3v3 amistoso"')
if (await tab('Chat').locator('.dot').count()) throw new Error('Mirando el chat, la solapa no tiene que marcar nada')
const autor = (n) => page.locator('.chat__autor', { hasText: n }).first()
if (!(await autor('Nico').locator('.en-linea').count())) throw new Error('Nico está conectado y no tiene el puntito verde')
if (await autor('Lucho').locator('.en-linea').count()) throw new Error('Lucho no está conectado y tiene el puntito verde')
const caja = page.getByRole('textbox', { name: 'Mensaje' })
await caja.fill('   ')
if (!(await boton('Enviar').isDisabled())) throw new Error('Un mensaje vacío no se puede mandar')
await caja.fill('hola, ¿quién juega?'); await caja.press('Enter')
await page.locator('.chat__msg', { hasText: 'hola, ¿quién juega?' }).waitFor()
if (await caja.inputValue() !== '') throw new Error('Después de mandar, la caja tiene que quedar vacía')
await caja.fill('Hola, ¿quién juega?'); await boton('Enviar').click()
await ver('Ya mandaste ese mensaje.'); await caja.fill('')
await foto('chat')
const mio = page.locator('.chat__msg', { hasText: 'hola, ¿quién juega?' })
if (await page.locator('.chat__msg', { hasText: 'voy' }).getByRole('button', { name: 'Borrar mensaje' }).count()) throw new Error('Sin moderar, solo se pueden borrar los mensajes propios')
await mio.getByRole('button', { name: 'Borrar mensaje' }).click()
await mio.getByRole('button', { name: 'Borrar', exact: true }).click()
await mio.waitFor({ state: 'detached' })
await boton('Moderar').click()
const ajeno = page.locator('.chat__msg', { hasText: 'qué buena la app' })
await ajeno.getByRole('button', { name: 'Borrar mensaje' }).click()
await ajeno.getByRole('button', { name: 'Borrar', exact: true }).click()
await ajeno.waitFor({ state: 'detached' })
await boton('Listo').click()
await page.getByRole('button', { name: 'Ver a Nico' }).first().click()
await page.getByRole('dialog', { name: 'Perfil de Nico' }).locator('.en-linea').waitFor()
await boton('Cerrar').click()
await tab('Perfil').click()
if (await tab('Chat').locator('.dot').count()) throw new Error('Después de leer el chat, la solapa no tiene que marcar nada')
await page.getByRole('link', { name: /^Amigos/ }).click()
await page.locator('.card--row', { hasText: 'Mati_' }).first().waitFor()
if (!(await page.locator('.card--row', { hasText: 'Mati_' }).first().locator('.en-linea').count())) throw new Error('En Amigos, Mati_ tiene que tener el puntito verde')
if (await page.locator('.card--row', { hasText: 'Lucho' }).first().locator('.en-linea').count()) throw new Error('En Amigos, Lucho no tiene que tener el puntito verde')
await boton('Volver').click()

paso('Kick: etiqueta al lado del nombre, en vivo en el Inicio, vincular y desvincular')
await tab('Inicio').click()
await page.getByRole('region', { name: 'En vivo en Kick' }).getByText('Amistosos 3v3 con la comunidad').waitFor()
if (!(await page.getByRole('link', { name: 'Ver el directo de Nico en Kick' }).getAttribute('href'))?.startsWith('https://kick.com/nico_hax')) throw new Error('El botón Ver tiene que llevar al canal de Kick')
await tab('Chat').click()
await page.locator('.chat__autor', { hasText: 'Cami_DC' }).first().locator('img.kick-logo').waitFor()
await page.locator('.chat__autor', { hasText: 'Nico' }).first().locator('.kick', { hasText: 'EN VIVO' }).waitFor()
// Tocar a quien está en vivo: su perfil muestra el directo, y tocándolo se va a su Kick.
await page.getByRole('button', { name: 'Ver a Nico' }).first().click()
const directo = page.getByRole('link', { name: 'Nico está en vivo en Kick. Ver el directo' })
await directo.getByText('Amistosos 3v3 con la comunidad').waitFor()
if (await directo.getAttribute('href') !== 'https://kick.com/nico_hax' || await directo.getAttribute('target') !== '_blank') throw new Error('El directo tiene que abrir su canal de Kick')
await page.waitForTimeout(500); await foto('perfil-en-vivo')
await boton('Cerrar').click()
await tab('Perfil').click()
const filaKick = page.locator('.card--row', { hasText: 'Kick' }).filter({ hasText: /Mostrá tu canal|Conectado como/ })
await filaKick.getByRole('button', { name: 'Vincular' }).click()
await filaKick.getByText('Conectado como eldemo_kick').waitFor()
await foto('kick-vinculado')
await filaKick.getByRole('button', { name: 'Quitar' }).click()
await filaKick.getByRole('button', { name: 'Desvincular' }).click()
await filaKick.getByRole('button', { name: 'Vincular' }).waitFor()

paso('ocultar que estoy conectado y panel de administración')
await tab('Perfil').click()
const visible = page.getByRole('switch', { name: 'Mostrar cuando estoy conectado' })
if (await visible.getAttribute('aria-checked') !== 'true') throw new Error('De entrada se muestra')
await visible.click(); await ver('Nadie ve si estás conectado.')
await visible.click(); await ver('Los demás ven un puntito verde')
await link('Panel de administración').click()
await ver('registrados'); await ver('Reportes de los últimos 30 días'); await ver('Últimos registrados')
await boton('Suspender').click(); await boton('3 días').click()
await page.getByLabel('Motivo').fill('Insultos en el chat')
await boton('Suspender · 3 días').click()
await ver('quedó suspendido (3 días)'); await foto('panel')
await boton('Volver').click()

paso('mi sala: elijo de la lista a quién invitar')
await tab('Inicio').click()
await link('Necesito un jugador').click()
// Primero la cancha: de ella dependen cuántos pueden faltar y qué posiciones hay.
if (!(await boton('Buscar jugador').isDisabled())) throw new Error('Sin cancha no se puede buscar')
if (await boton('Cualquiera').count()) throw new Error('En la sala no va la cancha "Cualquiera"')
await boton('Classic').click()
if (await boton('2').count() || await boton('GK').count()) throw new Error('En Classic no se elige cuántos faltan ni posición')
await boton('Big').click()
for (const f of ['1', '2']) await boton(f).waitFor()
if (await boton('3').count() || await boton('DFC').count()) throw new Error('En Big faltan hasta 2 y no hay DFC')
await boton('Futsal').click()
for (const f of ['1', '2', '3', '4', '5', '6']) await boton(f).waitFor()
await boton('LD').waitFor()
await boton('Real Soccer').click()
if (await boton('4').count() || await boton('LD').count()) throw new Error('En Real Soccer faltan hasta 3 y no hay laterales')
await boton('Big').click()
await page.getByLabel('Nombre de la sala').fill('sala demo')
await boton('2').click()
await foto('form-sala')
await boton('Buscar jugador').click()
await ver('Faltan 2 · ARG'); await noVer('¿Te avisamos?')
await ver('JUSTO'); await ver('Elegí a quién invitar'); await foto('sala-buscando')
// La app no acerca a nadie sola: hasta que no invito, no pasa nada.
await page.waitForTimeout(2500); await noVer('¿Aceptás a'); await noVer('va a entrar')
await fila('Tobi_GK').getByRole('button', { name: 'Invitar' }).click()
await fila('Tobi_GK').getByRole('button', { name: 'Invitado' }).waitFor(); await foto('sala-invitado')
await ver('Sala completa', 20000)

paso('sala llena: el reloj queda quieto')
await ver('Tocá “Ya entró Tobi_GK a la sala” cuando el jugador se encuentre dentro'); await page.waitForTimeout(400); await foto('sala-ya-entro')
const quieto = await page.getByRole('timer').innerText()
await page.waitForTimeout(2200)
if (await page.getByRole('timer').innerText() !== quieto) throw new Error('El reloj sigue corriendo con la sala completa')

paso('ya entró / todavía no / se salió')
await boton('Ya entró Tobi_GK a la sala').last().click()
await ver('Fede_7 va a entrar')
await boton('Todavía no').click()
await ver('En tu sala'); await ver('Aceptado · todavía no entró')
await ver('Amistoso confirmado · +10 puntos')
await ver('Adentro · confirmó'); await foto('sala-completa')
await boton('Tobi_GK se salió').click()
await ver('Se liberó el lugar de Tobi_GK'); await ver('Falta 1 · ARG'); await ver('Buscando jugador'); await foto('sala-se-salio')
const corre = await page.getByRole('timer').innerText()
await page.waitForTimeout(2200)
if (await page.getByRole('timer').innerText() === corre) throw new Error('El reloj no volvió a correr al liberarse un lugar')

paso('invitar a uno que dice que no, completar con otro y que se arme el match')
await fila('Pibe9').getByRole('button', { name: 'Invitar' }).click()
await ver('Pibe9 no puede ahora'); await fila('Pibe9').getByRole('button', { name: 'No puede' }).waitFor()
await fila('Cami_DC').getByRole('button', { name: 'Invitar' }).click()
await ver('Cami_DC va a entrar'); await ver('Sala completa')
await boton('Ya entró Cami_DC a la sala').last().click()
await ver('Buscando', 1000).catch(() => {})
await ver('Sala completa')
await boton('Ya entró Fede_7 a la sala').last().click()
await ver('Tu sala está completa'); await ver('La búsqueda terminó'); await page.waitForTimeout(400); await foto('match-sala-completa')
await link('Volver al inicio').click()
await ver('Quiero jugar un amistoso'); await noVer('Ya estás buscando'); await noVer('Tu sala está completa'); await noVer('Cancelá tu búsqueda actual')

paso('se salió después del match: la sala vuelve a buscar')
await tab('Perfil').click()
await page.getByRole('link', { name: /Notificaciones/ }).click()
await fila('Match listo: tu sala está completa').getByRole('link', { name: 'Ver' }).click()
await ver('Tu sala está completa')
await boton('Cami_DC se salió').click()
await ver('Buscando jugador'); await ver('Falta 1 · ARG')
await abajo()
await boton('Cerrar sala').click()
await ver('Quiero jugar un amistoso')
await tab('Perfil').click()
await noVer('Por confirmar')
await boton('Avanzar un día').click()
await page.getByRole('link', { name: /Nivel \d+\. Ver detalle/ }).click()
await ver('Llevás 2 días seguidos'); await nivel()
await boton('Volver').click()
await page.reload()
await ver('ElDemo')
await boton('Reiniciar datos de prueba').click()
await ver('Entrar con Discord')

paso('el grupo arma su sala cuando quiere y después invita al resto')
await entrar()
await buscarPartido()
await fila('Tobi_GK').getByRole('button', { name: 'Mensaje' }).click()
await ver('Tobi_GK y Fede_7 se sumaron a tu búsqueda')
await boton('Armar una sala con el grupo').click()
await ver('Son 3. Uno crea la sala en HaxBall'); await page.waitForTimeout(400); await foto('armar-sala')
await boton('Crear una sala entre nosotros y seguir buscando').click()
await boton('Crear sala').click()
await ver('Escribí el nombre de la sala')
await page.getByLabel('Nombre de la sala').fill('equipo demo')
await boton('3').click()
await boton('Crear sala').click()
await ver('Faltan 3 · ARG'); await ver('Buscando jugador')
await boton('Ya entró Tobi_GK a la sala').last().click()
await boton('Ya entró Fede_7 a la sala').last().click()
await fila('Mati_').getByRole('button', { name: 'Invitar' }).click()
await ver('Mati_ va a entrar', 20000)
await ver('Faltan 2 · ARG')
await boton('Ya entró Mati_ a la sala').last().click()
await ver('Amistoso confirmado · +10 puntos'); await foto('sala-de-equipo')
await abajo()
await boton('Cerrar sala').click()

paso('cartel de los 15 minutos')
await buscarPartido()
await abajo()
await boton('Simular que pasaron 15 minutos').click()
await ver('Pasaron 15 minutos'); await page.waitForTimeout(400); await foto('quince-minutos')
await boton('Renovar la búsqueda').click()
await ver('Búsqueda renovada'); await ver('Vence en 14:5')
await abajo()
await boton('Simular que pasaron 15 minutos').click()
await boton('Crear una sala y buscar jugadores').click()
await page.getByLabel('Nombre de la sala').fill('sala tardía')
await boton('4').click()
await boton('Crear sala').click()
await ver('Faltan 4 · ARG'); await ver('Sala "sala tardía"')
await abajo()
await boton('Cancelar búsqueda').click()
await ver('Quiero jugar un amistoso')
await tab('Perfil').click()
await boton('Reiniciar datos de prueba').click()

paso('me invitan, me sumo, y a los 15 minutos jugamos entre nosotros')
await entrar()
await boton('Quiero jugar un amistoso').click()
await ver('Buscando partido')
await tab('Clips').click()
await ver('Mati_ te escribió', 25000)
await boton('Aceptar').click()
await ver('Te sumaste a la búsqueda de Mati_')
await page.locator('.banner a').click()
await ver('Buscan con vos')
console.log('  reloj al sumarme:', await page.getByRole('timer').innerText())
await abajo()
await boton('Cancelar búsqueda').click()
await buscarPartido()
await fila('Mati_').getByRole('button', { name: 'Mensaje' }).click()
await ver('Mati_ se sumó a tu búsqueda')
await abajo()
await boton('Simular que pasaron 15 minutos').click()
await boton('Jugar un 1v1 entre nosotros').click()
await page.getByLabel('Nombre de la sala').fill('mano a mano')
await boton('Crear sala').click()
await ver('Sala completa')
await boton('Ya entró Mati_ a la sala').last().click()
await ver('Tu sala está completa')
await ver('Partido válido · +10 puntos'); await foto('entre-nosotros')
await link('Volver al inicio').click()
await tab('Perfil').click()
await boton('Cerrar sesión').click()
await boton('Sí, cerrar sesión').click()
await ver('Entrar con Discord')

await browser.close()
if (errores.length) { console.log('ERRORES DE CONSOLA:\n' + errores.join('\n')); process.exit(1) }
console.log('Recorrido completo, sin errores de consola.')
